// AUTO-GENERATED by scripts/parseTexts.js
// Do not edit manually. Run: node scripts/parseTexts.js
//
// Generated: 2026-03-23T21:43:14.684Z

export interface Stanza {
  number: number;
  text: string;
}

export interface ParittaContentData {
  folderName: string;
  paliRoman: Stanza[];
  paliMyanmar: Stanza[];
  translationEnglish: Stanza[];
  translationMyanmar: Stanza[];
  preambleEnglish: string;
  preambleMyanmar: string;
}

const parittaContent: Record<number, ParittaContentData> = {
  1: {
    folderName: '01_mangala_sutta',
    paliRoman: [
      { number: 1, text: `Bahū devā manussā ca maṅgalāni acintayuṃ ākankhamāna sotthānaṃ brūhi maṅgalamuttamaṃ` },
      { number: 2, text: `Asevanā ca bālānaṃ paṇḍitānañ ca sevanā pūjā ca pūjanīyānaṃ etaṃ maṅgalamuttamaṃ` },
      { number: 3, text: `Patirūpadesavāso ca pubbe ca katapuññatā attasammāpaṇidhi ca etaṃ maṅgalamuttamaṃ` },
      { number: 4, text: `Bāhusaccañ ca sippañ ca vinayo ca susikkhito subhāsitā ca yā vācā etaṃ maṅgalamuttamaṃ` },
      { number: 5, text: `Mātāpitū upatthānaṃ puttadārassa saṅgaho anākulā ca kammantā etaṃ maṅgalamuttamaṃ` },
      { number: 6, text: `Dānañ ca dhammacariyā ca ñātakānañ ca saṅgaho anavajjāni kammāni etaṃ maṅgalamuttamaṃ` },
      { number: 7, text: `ārati virati pāpā majjapānā ca saññamo appamādo ca dhammesu etaṃ maṅgalamuttamaṃ` },
      { number: 8, text: `Gāravo ca nivāto ca santuṭṭhī ca kataññutā kālena dhammasavanaṃ etaṃ maṅgalamuttamaṃ` },
      { number: 9, text: `Khantī ca sovacassatā samaṇānañ ca dassanaṃ kālena dhammasākacchā etaṃ maṅgalamuttamaṃ` },
      { number: 10, text: `Tapo ca brahmacariyañ ca ariyasaccānadassanaṃ nibbānasacchikiriyā ca etaṃ maṅgalamuttamaṃ` },
      { number: 11, text: `Phuṭṭhassa lokadhammehi cittaṃ yassa na kampati asokaṃ virajaṃ khemaṃ etaṃ maṅgalamuttamaṃ` },
      { number: 12, text: `Etādisāni katvāna sabbatthamaparājitā sabbattha sotthiṃ gacchanti taṃ tesaṃ maṅgalamuttaman’ti` },
    ],
    paliMyanmar: [
    ],
    translationEnglish: [
      { number: 1, text: `"Many deities and men longing for happiness have pondered on (the question of) blessings. Pray tell me what the highest blessings are.` },
      { number: 2, text: `"Not to associate with the foolish, but to associate with the wise, and to honor those worthy of honor — this is the highest blessing.` },
      { number: 3, text: `"To reside in a suitable locality, to have performed meritorious actions in the past, and to set oneself in the right direction — this is the highest blessing.` },
      { number: 4, text: `"Vast learning, skill in handicrafts, well grounded in discipline, and pleasant speech — this is the highest blessing.` },
      { number: 5, text: `"To support one's father and mother; to cherish one's wife and children, and to be engaged in peaceful occupations — this is the highest blessing.` },
      { number: 6, text: `"Liberality, righteous conduct, rendering assistance to relatives, and performance of blameless deeds — this is the highest blessing.` },
      { number: 7, text: `"To cease and abstain from evil, to abstain from intoxicating drinks, and diligent in performing righteous acts — this is the highest blessing.` },
      { number: 8, text: `"Reverence, humility, contentment, gratitude, and the timely hearing of the Dhamma, the teaching of the Buddha — this is the highest blessing.` },
      { number: 9, text: `"Patience, obedience, meeting the Samanas (holy men), and timely discussions on the Dhamma — this is the highest blessing.` },
      { number: 10, text: `"Self-control, chastity, comprehension of the Noble Truths, and the realization of Nibbana — this is the highest blessing.` },
      { number: 11, text: `"The mind that is not touched by the vicissitudes of life,[2] the mind that is free from sorrow, stainless, and secure — this is the highest blessing.` },
      { number: 12, text: `"Those who have fulfilled the conditions (for such blessings) are victorious everywhere, and attain happiness everywhere — To them these are the highest blessings."` },
    ],
    translationMyanmar: [
      { number: 1, text: `“ပျော်ရွှင်မှုကို တောင့်တသော နတ်သားနှင့် လူတို့သည် ကောင်းချီးမင်္ဂလာများကို ဆင်ခြင်သုံးသပ်ကြ၏။ အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာကား အဘယ်နည်းဟု အကျွန်ုပ်အား ပြောပြပါ။` },
      { number: 2, text: `“မိုက်မဲသောသူတို့နှင့် မပေါင်းသင်းဘဲ ပညာရှိတို့နှင့် ပေါင်းသင်းခြင်း၊ ရိုသေထိုက်သော သူတို့အား ရိုသေလေးစားခြင်းသည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာ ဖြစ်သည်။` },
      { number: 3, text: `“သင့်လျော်သော အရပ်၌ နေထိုင်ခြင်း၊ အတိတ်က ကောင်းမှုကုသိုလ်များကို ပြုလုပ်ခြင်း၊ မှန်ကန်သော လမ်းကြောင်းတွင် ရပ်တည်ခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာ ဖြစ်သည်။` },
      { number: 4, text: `“ကျယ်ပြန့်သော အသိပညာ၊ လက်မှုပညာတွင် ကျွမ်းကျင်ခြင်း၊ ကျင့်ဝတ်၌ ကောင်းစွာ ခိုင်မာခြင်း၊ သာယာသော စကားသည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာ ဖြစ်သည်။` },
      { number: 5, text: `မိဘကို ထောက်ပံ့ခြင်း၊ ဇနီးနှင့် သားသမီးများကို တန်ဖိုးထားခြင်း၊ ငြိမ်းချမ်းသော အလုပ်အကိုင်များတွင် ပါဝင်ဆောင်ရွက်ခြင်းသည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 6, text: `ရက်ရောခြင်း၊ ဖြောင့်မတ်စွာ ပြုမူခြင်း၊ ဆွေမျိုးများအား ကူညီခြင်း၊ အပြစ်ကင်းသော အကျင့်များကို ကျင့်ကြံခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 7, text: `မကောင်းမှုကို ရပ်တန့်၍ ရှောင်ကြဉ်ခြင်း၊ မူးယစ်သောက်စားခြင်းမှ ရှောင်ကြဉ်ခြင်း၊ ဖြောင့်မတ်သော အကျင့်များကို ကျင့်ကြံခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 8, text: `ရိုသေလေးစားခြင်း၊ နှိမ့်ချခြင်း၊ ကျေနပ်ခြင်း၊ ကျေးဇူးတင်ခြင်း၊ ဗုဒ္ဓ၏ တရားတော်ကို အချိန်မီ နာကြားနိုင်ခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 9, text: `သည်းခံခြင်း၊ နာခံခြင်း၊ သမဏများနှင့် တွေ့ဆုံခြင်း၊ ဓမ္မကို အချိန်မီ ဆွေးနွေးခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 10, text: `ကိုယ့်ကိုယ်ကိုယ် ထိန်းကျောင်းခြင်း၊ သီလစင်ကြယ်ခြင်း၊ အရိယာတို့၏ အမှန်တရားကို နားလည်ခြင်းနှင့် နိဗ္ဗာန်ကို မျက်မှောက်ပြုခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 11, text: `"ဘဝ၏ အပြောင်းအလဲများကြောင့် မထိခိုက်သောစိတ်၊[2] ဝမ်းနည်းမှုကင်းသော၊ အညစ်အကြေးကင်းစင်သော၊ လုံခြုံသောစိတ် - ဤသည်မှာ အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 12, text: `"(ထိုကဲ့သို့သော ကောင်းချီးမင်္ဂလာများအတွက်) အခြေအနေများနှင့် ပြည့်စုံသူများသည် နေရာတိုင်းတွင် အောင်ပွဲခံကြပြီး နေရာတိုင်းတွင် ပျော်ရွှင်မှုကို ရရှိကြသည် - ၎င်းတို့အတွက် ဤသည်မှာ အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာများဖြစ်သည်။"` },
    ],
    preambleEnglish: `Evam me sutam. Ekam samayam Bhagavā Sāvatthiyam viharati Jetavane Anāthapindikassa ārāme.
Atha kho aññātarā devatā abhikkantāya rattiyā abhikkanta vannā kevala kappam Jetavanam obhāsetvā yena Bhagavā tenupasamkami upasamkamitvā bhagavantam.
Abhivādetvā ekamantam atthāsi
Ekamantam thitā kho sā devatā Bhagavantam gāthāya ajjhabhāsi.`,
    preambleMyanmar: ``,
  },
  2: {
    folderName: '02_ratana_sutta',
    paliRoman: [
      { number: 1, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yā niva antaḷikkhe
Sabbeva bhūtā sumanā bhavantu
Athopi sakkacca sunantu bhāsitaṁ` },
      { number: 2, text: `Tasmā hi bhūtā nisāmetha sabbe
Mettaṁ karotha mānusiyā pajāya
Divā ca ratto ca haranti ye baliṁ
Tasmā hi ne rakkhatha appamattā` },
      { number: 3, text: `Yaṁ kiñci vittaṁ idha vā huraṁ vā
Saggesu vā yaṁ ratanaṁ paṇītaṁ
Na no samaṁ atthi Tathāgatena
Idampi Buddhe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 4, text: `Khayaṁ virāgaṁ amataṁ paṇītaṁ
Yadajjhagā Sakyamunī samāhito
Na tena Dhammena samatthi kiñci
Idampi Dhamme ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 5, text: `Yaṁ Buddhaseṭṭho parivaṇṇayī suciṁ
Samādimānantarikaññamāhu
Samādhinā tena samo na vijjati
Idampi Dhamme ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 6, text: `Ye puggalā aṭṭha sataṁ pasatthā
Cattāri etāni yugāni honti
Te dakkhiṇeyyā Sugatassa sāvakā
Etesu dinnāni mahapphalāni
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 7, text: `Ye suppayuttā manasā daḷhena
Nikkāmino Gotama sāsanamhi
Te pattipattā amataṁ vigayha
Laddhā mudhā nibbutiṁ bhuñjamānā
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 8, text: `Yathindakhīlo paṭhaviṁ sito siyā
Catubbhi vātebhi asampakampiyo
Tathūpamaṁ sappurisaṁ vadāmi
Yo ariyasaccāni avecca passati
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 9, text: `Ye ariyasaccāni vibhāvayanti
Gambhīrapaññena sudesitāni
Kiñcāpi te honti bhusappamattā
Na te bhavaṁ aṭṭhamaṁ ādiyanti
Idam’pi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 10, text: `Sahāva’ssa dassana sampadāya
Tayassu dhammā jahitā bhavanti
Sakkāyadiṭṭhi vicikicchitañ ca
Sīlabbataṁvā’pi yadatthi kiñci
Catūhapāyehi ca vippamutto,
Cha cābhiṭhānāni abhabbo kātuṁ
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 11, text: `Kiñcā’pi so kammaṁ karoti pāpakaṁ
Kāyena vācā uda cetasā vā
Abhabbo so tassa paṭicchādāya
Abhabbatā diṭṭha padassa vuttā
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 12, text: `Vanappagumbe yathā phussitagge
Gimhānamāse paṭhamasmiṁ gimhe
Tathūpamaṁ Dhamma varaṁ adesayi
Nibbāṇagāmiṁ paramaṁ hitāya
Idampi Buddhe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 13, text: `Varo varaññū varado varāharo
Anuttaro Dhamma varaṁ adesayi
Idampi Buddhe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 14, text: `Khīṇaṁ purāṇaṁ navaṁ natthi sambhavaṁ
virattacittā āyatike bhavasmiṁ
Te khīṇabījā avirūḷhicchandā
Nibbanti dhīrā yathāyaṁ padīpo
Idampi Saṅghe ratanaṁ paṇītaṁ,
Etena saccena suvatthi hotu` },
      { number: 15, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yāniva antaḷikkhe
Tathāgataṁ devamanussa pūjitaṁ
Buddhaṁ namassāma suvatthi hotu` },
      { number: 16, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yāniva antaḷikkhe
Tathāgataṁ devamanussa pūjitaṁ
Dhammaṁ namassāma suvatthi hotu` },
      { number: 17, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yāniva antaḷikkhe
Tathāgataṁ devamanussa pūjitaṁ
Saṅghaṁ namassāma suvatthi hotu` },
    ],
    paliMyanmar: [
      { number: 1, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိ ဝ အန္တလိက္ခေ။
သဗ္ဗေဝ ဘူတာ သုမနာ ဘဝန္တု၊
အထောပိ သက္ကစ္စ သုဏန္တု ဘာသိတံ။` },
      { number: 2, text: `တသ္မာဟိ ဘူတာ နိသာမေထ သဗ္ဗေ၊
မေတ္တံ ကရောထ မာနုသိယာ ပဇာယ။
ဒိဝါ စ ရတ္တော စ ဟရန္တိ ယေ ဗလိံ၊
တသ္မာ ဟိ နေ ရက္ခထ အပ္ပမတ္တာ။` },
      { number: 3, text: `ယံကိဉ္စိ ဝိတ္တံ ဣဓ ဝါ ဟုရံ ဝါ၊
သဂ္ဂေသု ဝါ ယံ ရတနံ ပဏီတံ၊
န နော သမံ အတ္ထိ တထာဂတေန၊
ဣဒမ္ပိ ဗုဒ္ဓေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 4, text: `ခယံ ဝိရာဂံ အမတံ ပဏီတံ၊
ယဒဇ္ဈ ဂါ သကျမုနီ သမာဟိတော။
န တေန ဓမ္မေန သမတ္ထိ ကိဉ္စိ၊
ဣဒမ္ပိ ဓမ္မေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 5, text: `ယံ ဗုဒ္ဓသေဋ္ဌော ပရိဝဏ္ဏယီ သုစိံ၊
သမာဓိ မာနန္တရိက ည မာဟု။
သမာဓိနာ တေန သမော န ဝိဇ္ဇတိ၊
ဣဒမ္ပိ ဓမ္မေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 6, text: `ယေ ပုဂ္ဂလာ အဋ္ဌ သတံ ပသတ္ထာ၊
စတ္တာရိ ဧတာနိ ယုဂါနိ ဟောန္တိ။
တေ ဒက္ခိဏေယျာ သုဂတဿ သာဝကာ၊
ဧတေသု ဒိန္နာနိ မဟပ္ဖလာနိ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္တိ ဟောတု။` },
      { number: 7, text: `ယေ သုပ္ပယုတ္တာ မနသာ ဒဠှေန၊
နိက္ကာ မိနော ဂေါတမသာသနမှိ။
တေ ပတ္တိပတ္တာ အမတံ ဝိဂယှ၊
လဒ္ဓါ မုဓာ နိဗ္ဗုတိံ ဘုဉ္ဇ မာနာ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 8, text: `ယထိန္ဒခီလော ပထဝိဿိတော သိယာ၊
စတုဗ္ဘိ ဝါတေဟိ အသမ္ပကမ္ပိယော။
တထူပမံ သပ္ပုရိသံ ဝဒါမိ။
ယော အရိယသစ္စာနိ အဝေစ္စ ပဿတိ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 9, text: `ယေအရိယ သစ္စာနိ ဝိဘာဝယန္တိ၊
ဂမ္ဘီရပညေန သုဒေသိတာနိ။
ကိဉ္စာပိ တေ ဟောန္တိ ဘုသံ ပမတ္တာ၊
န တေ ဘဝံ အဋ္ဌမ မာဒိယန္တိ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 10, text: `သဟာဝဿ ဒဿန သမ္ပဒါယ၊
တယဿု ဓမ္မာ ဇဟိတာ ဘဝန္တိ။
သက္ကာယဒိဋ္ဌီ ဝိစိကိစ္ဆိတဉ္စ၊
သီလဗ္ဗတံ ဝါပိ  ယဒတ္ထိ ကိဉ္စိ။
စတူဟပါယေဟိ စ ဝိပ္ပမုတ္တော၊
ဆစ္စာဘိဌာနာနိ အဘဗ္ဗ ကာတုံ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 11, text: `ကိဉ္စာပိ သော ကမ္မကရောတိ ပါပကံ၊
ကာယေန ဝါစာ ဥဒ စေတသာ ဝါ၊
အဘဗ္ဗ သော တဿ ပဋိစ္ဆဒါယ၊
အဘဗ္ဗတာ ဒိဋ္ဌပဒဿာ ဝုတ္တာ၊
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ။
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 12, text: `ဝနပ္ပဂုမ္ဗေ ယထ ဖုဿိတဂ္ဂေ၊
ဂိမှာန မာသေ ပဌမသ္မိံ ဂိမှေ။
တထူပမံ ဓမ္မဝရံ အဒေသယိ၊
နိဗ္ဗာနဂါမိံ ပရမံ ဟိတာယ။
ဣဒမ္ပိ ဗုဒ္ဓေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 13, text: `ဝရော ဝရညူ ဝရဒေါ ဝရာဟရော၊
အနုတ္တရော ဓမ္မဝရံ အဒေသယိ။
ဣဒမ္ပိ ဗုဒ္ဓေ ရတနံ ပဏီတံ။
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 14, text: `ခီဏံ ပုရာဏံ နာဝ နတ္ထိ သမ္ဘဝံ၊
ဝိရတ္တစိတ္တာယတိကေ ဘဝသ္မိံ။
တေ ခီဏဗီဇာ အဝိရူဠိဆန္ဒာ၊
နိဗ္ဗန္တိ ဓီရာ ယထာယံ ပဒီပေါ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 15, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိ ဝ အန္တ လိက္ခေ။
တထာဂတံ ဒေဝမနုဿ ပူဇိတံ၊
ဗုဒ္ဓံ နမဿာမ သုဝတ္ထိ ဟောတု။` },
      { number: 16, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိဝ အန္တ လိက္ခေ။
တထာဂတံ ဒေဝမနုဿပူဇိတံ၊
ဓမ္မံ နမဿာမ သုဝတ္ထိ ဟောတု။` },
      { number: 17, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိ ဝ အန္တ လိက္ခေ။
တထာဂတံ ဒေဝမနုဿ ပူဇိတံ၊
သံဃံ နမဿာမ သုဝတ္ထိ ဟောတု။` },
    ],
    translationEnglish: [
      { number: 1, text: `"Whatever beings (non-humans) are assembled here, terrestrial or celestial, may they all have peace of mind, and may they listen attentively to these words."` },
      { number: 2, text: `"O beings, listen closely. May you all radiate loving-kindness to those human beings who, by day and night, bring offerings to you (offer merit to you). Wherefore, protect them with diligence."` },
      { number: 3, text: `"Whatever treasure there be either in the world beyond, whatever precious jewel there be in the heavenly worlds, there is nought comparable to the Tathagata (the perfect One). This precious jewel is the Buddha.[4] By this (asseveration of the) truth may there be happiness."` },
      { number: 4, text: `"That Cessation, that Detachment, that Deathlessness (Nibbana) supreme, the calm and collected Sakyan Sage (the Buddha) had realized. There is nought comparable to this (Nibbana) Dhamma. This precious jewel is the Dhamma.[5] By this (asseveration of the) truth may there be happiness."` },
      { number: 5, text: `"The Supreme Buddha extolled a path of purity (the Noble Eightfold Path) calling it the path which unfailingly brings concentration. There is nought comparable to this concentration. This precious jewel is the Dhamma. By this (asseveration of the) truth may there be happiness."` },
      { number: 6, text: `"The eight persons extolled by virtuous men constitute four pairs. They are the disciples of the Buddha and are worthy of offerings. Gifts given to them yield rich results. This precious jewel is the Sangha.[6] By this (asseveration of the) truth may there be happiness."` },
      { number: 7, text: `"With a steadfast mind, and applying themselves well in the dispensation of the Buddha Gotama, free from (defilements), they have attained to that which should be attained (arahantship) encountering the Deathless. They enjoy the Peace of Nibbana freely obtained.[7] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 8, text: `"As a post deep-planted in the earth stands unshaken by the winds from the four quarters, so, too, I declare is the righteous man who comprehends with wisdom the Noble Truths. This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 9, text: `"Those who realized the Noble Truths well taught by him who is profound in wisdom (the Buddha), even though they may be exceedingly heedless, they will not take an eighth existence (in the realm of sense spheres).[8] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 10, text: `"With his gaining of insight he abandons three states of mind, namely self-illusion, doubt, and indulgence in meaningless rites and rituals, should there be any. He is also fully freed from the four states of woe, and therefore, incapable of committing the six major wrongdoings.[9] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 11, text: `"Any evil action he may still do by deed, word or thought, he is incapable of concealing it; since it has been proclaimed that such concealing is impossible for one who has seen the Path (of Nibbana).[10] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 12, text: `"As the woodland groves though in the early heat of the summer month are crowned with blossoming flowers even so is the sublime Dhamma leading to the (calm) of Nibbana which is taught (by the Buddha) for the highest good. This precious jewel is the Buddha. By this (asseveration of the) truth may there be happiness."` },
      { number: 13, text: `"The Peerless Excellent one (the Buddha) the Knower (of Nibbana), the Giver (of Nibbana), the Bringer (of the Noble Path), taught the excellent Dhamma. This precious jewel is the Buddha. By this (asseveration of the) truth may there be happiness."` },
      { number: 14, text: `"Their past (kamma) is spent, their new (kamma) no more arises, their mind to future becoming is unattached. Their germ (of rebirth-consciousness) has died, they have no more desire for re-living. Those wise men fade out (of existence) as the flame of this lamp (which has just faded away). This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 15, text: `"Whatever beings are assembled here, terrestrial or celestial, come let us salute the Buddha, the Tathagata, honored by gods and men. May there be happiness."` },
      { number: 16, text: `"Whatever beings are assembled here terrestrial or celestial, come let us salute the perfect Dhamma, honored by gods and men. May there be happiness."` },
      { number: 17, text: `"Whatever beings are assembled here terrestrial or celestial, come let us salute the perfect Sangha, honored by gods and men. May there be happiness."` },
    ],
    translationMyanmar: [
      { number: 1, text: `“မြေကြီးဖြစ်စေ၊ ကောင်းကင်ဖြစ်စေ ဤနေရာတွင် စုဝေးနေသော သတ္တဝါအားလုံး စိတ်၏ချမ်းသာမှုကို ရရှိကြပါစေ၊ ဤစကားများကို အာရုံစိုက် နားထောင်နိုင်ကြပါစေ။` },
      { number: 2, text: `“အို သတ္တဝါတို့၊ သေချာစွာ နားထောင်ကြလော့။ နေ့ရောညပါ သင်တို့အား ပူဇော်သက္ကာများ ယူဆောင်လာသူများ (သင်တို့အား ကုသိုလ်များ ပေးဆောင်ကြလော့)၊ ထို့ကြောင့် သင်တို့အား ဂရုတစိုက် ကာကွယ်စောင့်ရှောက်ကြလော့။` },
      { number: 3, text: `"တမလွန်လောက၌ ရတနာတစ်စုံတစ်ရာရှိပါစေ၊ နတ်ပြည်၌ ရတနာတစ်စုံတစ်ရာရှိပါစေ၊ တထာဂတ (ပြီးပြည့်စုံသော) ပုဂ္ဂိုလ်နှင့် နှိုင်းယှဉ်၍မရပါ။ ဤရတနာသည် ဗုဒ္ဓဖြစ်သည်။[၄] ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ကြောင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 4, text: `"ထိုချုပ်ငြိမ်းခြင်း၊ ထိုကင်းကွာခြင်း၊ ထိုသေခြင်း (နိဗ္ဗာန်) သည် မြင့်မြတ်သော၊ ငြိမ်သက်ပြီး စုစည်းထားသော သကျသာကီဝင်မင်း (ဗုဒ္ဓ) သိမြင်တော်မူသော ချမ်းသာသုခ။ ဤ (နိဗ္ဗာန်) ဓမ္မနှင့် နှိုင်းယှဉ်၍မရပါ။ ဤရတနာသည် ဓမ္မဖြစ်သည်။[၅] ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ကြောင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 5, text: `"အမြင့်မြတ်ဆုံးသော ဗုဒ္ဓသည် ဖြူစင်သော လမ်းစဉ် (အရိယာရှစ်ပါး) ကို ချီးမြှောက်တော်မူပြီး မပြတ်တည်တံ့သော လမ်းစဉ်ကို ခေါ်ဆို၍ သမာဓိကို ဆောင်ကြဉ်းပေးသည်။ ဤသမာဓိနှင့် နှိုင်းယှဉ်၍မရပါ။ ဤရတနာသည် ဓမ္မဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ကြောင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 6, text: `"သီလရှိသော ပုဂ္ဂိုလ်ရှစ်ဦးသည် လေးစုံဖြစ်သည်။ ၎င်းတို့သည် ဗုဒ္ဓ၏ တပည့်များဖြစ်ပြီး ပူဇော်ထိုက်သူများ ဖြစ်ကြသည်။" သူတို့အားပေးသော အလှူဒါနများသည် ကြွယ်ဝသော အကျိုးကျေးဇူးများကို ရရှိစေပါသည်။ ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။[၆] ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 7, text: `“တည်ကြည်သောစိတ်ဖြင့် ဂေါတမဗုဒ္ဓ၏ သာသနာတော်တွင် ကောင်းစွာ ကြိုးစားအားထုတ်၍ (ကိလေသာမှ ကင်းစင်) ရသင့်ရထိုက်သော အရဟတ္တမဘုံသို့ ရောက်ရှိကြပြီး မသေနိုင်သော နိဗ္ဗာန်ကို တွေ့ကြုံခံစားကြသည်။” [၇] ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 8, text: `“မြေကြီး၌ နက်ရှိုင်းစွာ စိုက်ထားသော တိုင်သည် အရပ်လေးမျက်နှာမှ လေတိုက်ခတ်မှုဒဏ် မခံရသကဲ့သို့၊ ဉာဏ်ပညာဖြင့် အရိယာသစ္စာတရားကို နားလည်သော သူတော်ကောင်းလည်း ဖြစ်သည်ဟု ငါ မိန့်ကြား၏။ ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 9, text: `"ဉာဏ်ပညာနှင့်ပြည့်စုံတော်မူသော (ဗုဒ္ဓ) ကောင်းစွာ ဟောကြားတော်မူသော အရိယာသစ္စာတရားများကို သဘောပေါက်သူတို့သည် အလွန်သတိမဲ့နေသော်လည်း (အာရုံငါးပါးတွင်) ရှစ်ပါးသောဘဝသို့ မရောက်နိုင်ကြပေ။" [၈] ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို) သိမြင်ခြင်းဖြင့် ပျော်ရွှင်မှု ရှိပါစေ။` },
      { number: 10, text: `"ဉာဏ်အမြင်ရရှိခြင်းဖြင့် စိတ်အခြေအနေသုံးမျိုးကို စွန့်လွှတ်သည်။ ၎င်းမှာ မိမိကိုယ်ကိုယ် အထင်မှားခြင်း၊ သံသယနှင့် အဓိပ္ပာယ်မရှိသော ထုံးတမ်းစဉ်လာများတွင် နစ်မွန်းခြင်း ဖြစ်သည်။ သူသည် ဆင်းရဲဒုက္ခလေးမျိုးမှလည်း လုံးဝလွတ်မြောက်ပြီး ထို့ကြောင့် အဓိကအမှားခြောက်မျိုးကို ကျူးလွန်နိုင်ခြင်းမရှိပေ။" [၉] ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို) သိမြင်ခြင်းဖြင့် ပျော်ရွှင်မှု ရှိပါစေ။` },
      { number: 11, text: `"သူသည် လုပ်ရပ်၊ စကား သို့မဟုတ် အတွေးဖြင့် မကောင်းမှုကို ပြုလုပ်နေသေးပါက၊ ၎င်းကို ဖုံးကွယ်၍မရပါ။ နိဗ္ဗာန်လမ်းကို မြင်တွေ့ပြီးသူအတွက် ထိုသို့ဖုံးကွယ်ခြင်းသည် မဖြစ်နိုင်ဟု ကြေငြာထားသောကြောင့်ဖြစ်သည်။" [၁၀] ဤအဖိုးတန်ရတနာမှာ သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) အားဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 12, text: `"နွေရာသီ၏ အပူရှိန်တွင် တောအုပ်များသည် ပွင့်လန်းသော ပန်းများဖြင့် ဖုံးလွှမ်းနေသကဲ့သို့၊ မြတ်သောအကျိုးအတွက် (ဗုဒ္ဓ) ဟောကြားတော်မူသော နိဗ္ဗာန်၏ (ငြိမ်သက်ခြင်း) သို့ ပို့ဆောင်ပေးသော မြင့်မြတ်သောတရားလည်း ရှိပါသည်။ ဤအဖိုးတန်ရတနာမှာ ဗုဒ္ဓဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) အားဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 13, text: `"တုနှိုင်းမဲ့သော မြတ်သော (ဗုဒ္ဓ)၊ (နိဗ္ဗာန်ကို သိတော်မူသော)၊ (နိဗ္ဗာန်ကို ပေးသနားတော်မူသော)၊ (မြတ်သောလမ်းကို ဆောင်တော်မူသော)၊ မြတ်သောတရားကို ဟောကြားတော်မူခြင်း"` },
      { number: 14, text: `"သူတို့၏ အတိတ် (ကံ) ကုန်ဆုံးသွားပါပြီ၊ သူတို့၏ အသစ် (ကံ) မဖြစ်ပေါ်တော့ပါ၊ အနာဂတ်ဘဝအတွက် သူတို့၏ စိတ်သည် မတွယ်တာတော့ပါ။ သူတို့၏ ပဋိသန္ဓေစိတ် (ပဋိသန္ဓေစိတ်) သေသွားပါပြီ၊ သူတို့သည် ပြန်လည်ရှင်သန်လိုသော ဆန္ဒ မရှိတော့ပါ။ ထိုပညာရှိတို့သည် (ယခုမှ မှေးမှိန်သွားသော) ဤမီးခွက်၏ မီးလျှံကဲ့သို့ ပျောက်ကွယ်သွားပါသည်။ ဤအဖိုးတန်ရတနာသည် သံဃာတော်ဖြစ်သည်။ ဤ (သစ္စာတရားကို) ဖြင့် ပျော်ရွှင်မှု ရှိပါစေ။"` },
      { number: 15, text: `"ဤနေရာ၌ စုဝေးနေသော သတ္တဝါအားလုံး၊ နတ်နှင့်လူတို့ ရိုသေလေးစားခံရသော တထာဂတ ဗုဒ္ဓကို လာ၍ ရှိခိုးကြကုန်အံ့။ ပျော်ရွှင်မှု ရှိပါစေ။"` },
      { number: 16, text: `"ဤနေရာ၌ စုဝေးနေသော သတ္တဝါအားလုံး၊ နတ်နှင့်လူတို့ ရိုသေလေးစားခံရသော ပြီးပြည့်စုံသော တရားကို လာ၍ ရှိခိုးကြကုန်အံ့။ ပျော်ရွှင်မှု ရှိပါစေ။"` },
      { number: 17, text: `"ဤနေရာ၌ စုဝေးနေသော သတ္တဝါအားလုံး၊ နတ်နှင့်လူတို့ ရိုသေလေးစားခံရသော ပြီးပြည့်စုံသော သံဃာတော်ကို လာ၍ ရှိခိုးကြကုန်အံ့။ ပျော်ရွှင်မှု ရှိပါစေ။"` },
    ],
    preambleEnglish: `The city of Vesali was afflicted by a famine, causing death, especially to the poor folk. Due to the presence of decaying corpses the evil spirits began to haunt the city; this was followed by a pestilence. Plagued by these three fears of famine, non-human beings and pestilence, the citizens sought the help of the Buddha who was then living at Rajagaha.

Followed by a large number of monks including the Venerable Ananda, his attendant disciple, the Buddha came to the city of Vesali. With the arrival of the Master, there were torrential rains which swept away the putrefying corpses. The atmosphere became purified, the city was clean.

Thereupon the Buddha delivered this Jewel Discourse to the Venerable Ananda, and gave him instructions as to how he should tour the city with the Licchavi citizens reciting the discourse as a mark of protection to the people of Vesali. The Venerable Ananda followed the instructions, and sprinkled the sanctified water from the Buddha's own alms bowl. As a consequence the evil spirits were exorcised, the pestilence subsided. Thereafter the Venerable Ananda returned with the citizens of Vesali to the Public hall where the Buddha and his disciples had assembled awaiting his arrival. There the Buddha recited the same Jewel Discourse to the gathering:`,
    preambleMyanmar: `ပဏိဓာနတော ပဋ္ဌာယ တထာ ဂတဿ ဒသ ပါရမိယော,
ဒသ ဥပပါရမိယော, ဒသ ပရမတ္ထ ပါရမိယောတိ
သမတ္တိံသ ပါရမိယော, ပဉ္စ မဟာပရိစ္စာဂေ,
လောကတ္ထစရိယံ ဉာတတ္ထစရိယံ
ဗုဒ္ဓတ္ထစရိယန္တိ တိဿော စရိယာယော၊
ပစ္ဆိမဘဝေ ဂဗ္ဘဝေါက္ကန္တိံ၊ ဇာတိံ အဘိနိက္ခမနံ၊
ပဓာနစရိယံ ဗောဓိပလ္လင်္ကေ မာရဝိဇယံ သဗ္ဗညုတညာဏပ္ပဋိဝေဓံ။
ဓမ္မစက္ကပ္ပဝတ္တနံ, နဝ လောကုတ္တရ ဓမ္မေတိ၊ သဗ္ဗေပိ မေ ဗုဒ္ဓဂုဏေ၊
အာဝဇ္ဇေ တွာ ဝေသာ လိယာ တီသု ပါကာရန္တ ရေသု
တိယာမရတ္တိံ ပရိတ္တံ ကရောန္တော အာယသ္မာ အာနန္ဒတ္ထေ ရောဝိယ၊
ကာရုညစိတ္တံ ဥပဋ္ဌပေတွာ —

ကောဋီသတသဟဿေသု၊ စက္ကဝါဠေသု ဒေဝတာ။
ယဿာဏံ ပဋိဂ္ဂဏှန္တိ၊ ယဉ္စ ဝေသာလိယာ ပုရေ။

ရောဂါမနုဿဒုဗ္ဘိက္ခ−သမ္ဘူတံ တိဝိဓံ ဘယံ။
ခိပ္ပ မန္တရဓာပေသိ၊ ပရိတ္တံ တံ ဘဏာမဟေ။`,
  },
  3: {
    folderName: '03_metta_sutta',
    paliRoman: [
    ],
    paliMyanmar: [
      { number: 1, text: `ယဿာနုဘာဝတော ယက္ဓာ၊ နေဝ ဒေဿေန္တိ ဘီသနံ။
ယဉှိ  စေဝါနုယုဉ္ဇန္တော၊ ရတ္တိန္ဒိဝ မတန္ဒိတော။` },
      { number: 2, text: `သုခံ သုပတိ သုတ္တော စ၊ ပါပံ ကိဉ္စိ န ပဿတိ။
ဧဝမာဒိဂုဏူပေတံ၊ ပရိတ္တံ တံ ဘဏာမ ဟေ။` },
      { number: 3, text: `ကရဏီယ’ မတ္ထ ကုသလေန၊ ယန္တ သန္တံ ပဒံ အဘိသမေစ္စ။
သက္ကော ဥဇူ စ သုဟုဇူ စ၊ သုဝစော စဿ မုဒု အနတိ မာနီ။` },
      { number: 4, text: `သန္တုဿကော စ သုဘရော စ၊ အပ္ပကိစ္စော စ သလ္လဟုကဝုတ္တိ။
သန္တိန္ဒြိယော စ နိပကောစ၊ အပ္ပဂဗ္ဘော ကုလေသွ’ နနုဂိဒ္ဓေါ။` },
      { number: 5, text: `န စ ခုဒ္ဒ’မာစရေ ကိဉ္စိ၊ ယေန ဝိညူ ပရေ ဥပဝဒေယျုံ။
သုခိနော ဝ ခေမိနော ဟောန္တု၊ သဗ္ဗသတ္တာ ဘဝန္တု သုခိတတ္တာ။` },
      { number: 6, text: `ယေ ကေစိ ပါဏဘူတတ္ထိ၊ တသာ ဝါ ထာဝရာဝ’ နဝသေသာ။
ဒီဃာ ဝါ ယေဝ မဟန္တာ၊ မဇ္ဈိမာ ရဿကာ အဏုကထူလာ။` },
      { number: 7, text: `ဒိဋ္ဌာ ဝါ ယေဝ အဒိဋ္ဌာ၊ ယေ ဝ ဒူရေ ဝသန္တိ အဝိဒူရေ။
ဘူတာ ဝ သမ္ဘဝေသီ ဝ၊ သဗ္ဗသတ္တာ ဘဝန္တု သုခိတတ္တာ။` },
      { number: 8, text: `န ပရော ပရံ နိကုဗ္ဗေထ၊ နာတိမညေထ ကတ္ထစိ နကိဉ္စိ။
ဗျာရောသနာ ပဋိဃသည၊ နာညမညဿ ဒုက္ခ မိစ္ဆေယျ။` },
      { number: 9, text: `မာတာ ယထာ နိယံ ပုတ္တ၊ မာယုသာ ဧကပုတ္တ’ မနုရက္ခေ။
ဧဝမ္ပိ သဗ္ဗဘူတေသု၊ မာနသံ ဘာဝယေ အပရိမာဏံ။` },
      { number: 10, text: `မေတ္တဉ္စ သဗ္ဗလောကသ္မိ၊ မာနသံ ဘာဝယေ အပရိမာဏံ။
ဥဒ္ဓံ အဓော စ တိရီယဉ္စ၊ အသမ္ဗာဓံ အဝေရ’ မသပတ္တံ။` },
      { number: 11, text: `တိဋ္ဌံ စရံ နိသိန္နော ဝ၊ သယာနော ယာဝတာ’ဿ ဝိတမိဒ္ဓေါ။
ဧတံ သတိံ အဓိဋ္ဌေယျ၊ ဗြဟ္မ မေတံ ဝိဟာရ မိဓ မာဟု။` },
      { number: 12, text: `ဒိဋ္ဌိဉ္စ အနုပဂ္ဂမ္မ၊ သီလဝါ ဒဿနေန သမ္ပန္နော။
ကာမေသု ဝိနေယျ ဂေဓံ၊ နဟိ ဇာတု’ဂ္ဂဗ္ဘသေယျ ပုန ရေတိ။` },
    ],
    translationEnglish: [
      { number: 1, text: `"He who is skilled in (working out his own) well being, and who wishes to attain that state of Calm (Nibbana) should act thus: he should be dexterous, upright, exceedingly upright, obedient, gentle, and humble.` },
      { number: 2, text: `"Contented, easily supportable, with but few responsibilities, of simple livelihood, controlled in the senses, prudent, courteous, and not hanker after association with families.` },
      { number: 3, text: `"Let him not perform the slightest wrong for which wise men may rebuke him. (Let him think:) 'May all beings be happy and safe. May they have happy minds.'` },
      { number: 4, text: `& 5. "Whatever living beings there may be — feeble or strong (or the seekers and the attained) long, stout, or of medium size, short, small, large, those seen or those unseen, those dwelling far or near, those who are born as well as those yet to be born — may all beings have happy minds.` },
      { number: 6, text: `"Let him not deceive another nor despise anyone anywhere. In anger or ill will let him not wish another ill.` },
      { number: 7, text: `"Just as a mother would protect her only child with her life even so let one cultivate a boundless love towards all beings.` },
      { number: 8, text: `"Let him radiate boundless love towards the entire world — above, below, and across — unhindered, without ill will, without enmity.` },
      { number: 9, text: `"Standing, walking, sitting or reclining, as long as he is awake, let him develop this mindfulness. This, they say, is 'Noble Living' here.` },
      { number: 10, text: `"Not falling into wrong views — being virtuous, endowed with insight, lust in the senses discarded — verily never again will he return to conceive in a womb."` },
    ],
    translationMyanmar: [
      { number: 1, text: `"(ကိုယ့်ရဲ့ကိုယ်ပိုင်) ကောင်းကျိုးချမ်းသာကို လုပ်ဆောင်ရာမှာ ကျွမ်းကျင်ပြီး အဲဒီ ငြိမ်းချမ်းမှု (နိဗ္ဗာန်) ကို ရရှိလိုသူသည် ဒီလိုလုပ်ဆောင်သင့်ပါတယ်- လိမ္မာပါးနပ်သူ၊ ဖြောင့်မတ်သူ၊ အလွန်ဖြောင့်မတ်သူ၊ နာခံတတ်သူ၊ နူးညံ့သိမ်မွေ့သူ၊ နှိမ့်ချသူ ဖြစ်သင့်ပါတယ်။` },
      { number: 2, text: `"ကျေနပ်ရောင့်ရဲတတ်သူ၊ ထောက်ပံ့ရလွယ်ကူသူ၊ တာဝန်အနည်းငယ်သာရှိသူ၊ ရိုးရှင်းတဲ့ အသက်မွေးဝမ်းကျောင်းလုပ်ငန်းလုပ်ကိုင်သူ၊ အာရုံငါးပါးကို ထိန်းချုပ်နိုင်သူ၊ သတိရှိရှိ၊ ယဉ်ကျေးသူ၊ မိသားစုနဲ့ ပေါင်းသင်းဆက်ဆံလိုစိတ် မရှိသူ ဖြစ်ရပါမယ်။` },
      { number: 3, text: `"ပညာရှိတွေ ဆုံးမနိုင်တဲ့ အနည်းငယ်သော အမှားကို မပြုလုပ်ပါစေနဲ့။ (သူ တွေးပါစေ:) 'သတ္တဝါအားလုံး ပျော်ရွှင်လုံခြုံကြပါစေ။ ပျော်ရွှင်တဲ့စိတ်တွေ ရှိကြပါစေ' လို့ တွေးပါ။"` },
      { number: 4, text: `နှင့် ၅။ “မည်သည့်သက်ရှိသတ္တဝါမဆို - အားနည်းသည်ဖြစ်စေ၊ ခွန်အားကြီးသည်ဖြစ်စေ၊ (ရှာဖွေသူများနှင့် ရရှိသူများ) ရှည်သည်ဖြစ်စေ၊ သန်မာသည်ဖြစ်စေ၊ အလတ်စားသည်ဖြစ်စေ၊ တိုသည်ဖြစ်စေ၊ သေးငယ်သည်ဖြစ်စေ၊ ကြီးမားသည်ဖြစ်စေ၊ မြင်သည်ဖြစ်စေ၊ မမြင်သည်ဖြစ်စေ၊ အဝေးတွင်ဖြစ်စေ၊ အနီးတွင်ဖြစ်စေ၊ မွေးဖွားပြီးသူများနှင့် မမွေးဖွားသေးသူများဖြစ်စေ - သတ္တဝါအားလုံးသည် ချမ်းသာသောစိတ်ရှိပါစေ။` },
      { number: 6, text: `“သူသည် အခြားသူတစ်ဦးကို မလှည့်ဖြားပါနှင့်၊ မည်သည့်နေရာတွင်မဆို မည်သူ့ကိုမျှ မထီမဲ့မြင်မပြုပါနှင့်။ ဒေါသ သို့မဟုတ် မကောင်းမှုဖြင့် အခြားသူတစ်ဦးကို မကောင်းမှုပြုလိုခြင်းမရှိပါစေနှင့်။` },
      { number: 7, text: `“မိခင်သည် မိမိ၏တစ်ဦးတည်းသောသားကို အသက်ဖြင့်ကာကွယ်သကဲ့သို့ပင် သတ္တဝါအားလုံးအပေါ် အကန့်အသတ်မရှိသော မေတ္တာကို မွေးမြူပါစေ။` },
      { number: 8, text: `“သူသည် အထက်၊ အောက်၊ တစ်ဖက်တစ်ချက်ရှိ လောကတစ်ခုလုံးအပေါ် အတားအဆီးမရှိသော မေတ္တာကို ဖြန့်ကျက်ပါစေ။ မကောင်းသောဆန္ဒမရှိဘဲ ရန်ငြိုးမရှိဘဲ။` },
      { number: 9, text: `“ရပ်နေခြင်း၊ လမ်းလျှောက်ခြင်း၊ ထိုင်နေခြင်း၊ လဲလျောင်းနေခြင်း၊ နိုးနေသမျှကာလပတ်လုံး ဤသတိပဋ္ဌာန်ကို မွေးမြူပါစေ။ ဤသည်မှာ ‘မြင့်မြတ်သောဘဝ’ ဖြစ်သည်ဟု ဆိုကြသည်။` },
      { number: 10, text: `"မှားယွင်းသောအမြင်များ - သီလနှင့်ပြည့်စုံခြင်း၊ ဉာဏ်အမြင်နှင့်ပြည့်စုံခြင်း၊ အာရုံငါးပါးတို့၌ တပ်မက်မှုကို ပယ်ရှားခြင်း - ထိုသူသည် နောက်တစ်ဖန် သားအိမ်၌ ပဋိသန္ဓေတည်ရန် ပြန်မလာတော့ပါ။"` },
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
  4: {
    folderName: '04_khandha_sutta',
    paliRoman: [
    ],
    paliMyanmar: [
      { number: 1, text: `သဗ္ဗာသီဝိသ ဇာတီနံ၊ ဒိဗ္ဗမန္တာဂဒံ ဝိယ။
ယံ နာသေတိ ဝိသံ ဃောရံ၊ သေသဉ္စာပိ ပရိဿယံ။` },
      { number: 2, text: `အာဏာက္ခေတ္တမှိ သဗ္ဗတ္ထ၊ သဗ္ဗဒါ သဗ္ဗပါဏိနံ။
သဗ္ဗသောပိ နိဝါရေတိ၊ ပရိတ္တံ တံ ဘဏာမ ဟေ။` },
      { number: 3, text: `ဝိရူပက္ခေဟိ မေ မေတ္တံ၊ မေတ္တံ ဧရာပထေဟိ မေ။
ဆဗျာပုတ္တေ ဟိ မေ မေတ္တံ၊ မေတ္တံ ကဏှာ ဂေါတမ ကေဟိစ။` },
      { number: 4, text: `အပါဒကေဟိ မေ မေတ္တံ၊ မေတ္တံဒွိပါ ဒကေဟိ မေ။
စတုပ္ပဒေဟိ မေ မေတ္တံ၊ မေတ္တံ ဗဟုပ္ပဒေ ဟိ မေ။` },
      { number: 5, text: `မာ မံ အပါဒကော ဟိံသိ၊ မာ မံ ဟိံသိ ဒွိပါဒကော။
မာ မံ စတုပ္ပဒေါ ဟိံသိ၊ မာ မံ ဟိံသိ ဗဟုပ္ပဒေါ။` },
      { number: 6, text: `သဗ္ဗေ သတ္တာ သဗ္ဗေ ပါဏာ၊ သဗ္ဗေ ဘူတာ စ ကေဝလာ။
သဗ္ဗေ ဘဒြာနိ ပဿန္တု၊ မာ ကိဉ္စိ ပါပ မာဂမာ။` },
      { number: 7, text: `အပ္ပမာဏော ဗုဒ္ဓေါ၊ အပ္ပမာဏော ဓမ္မော။
အပ္ပမာဏော သံဃော၊ ပမာဏဝန္တာနိ သရီသပါနိ။
အဟိ ဝိစ္ဆိကာ သတပဒီ၊ ဥဏ္ဏနာဘီ သရဗူ မူသိကာ။` },
      { number: 8, text: `ကတာ မေ ရက္ခာ ကတံ မေ ပရိတ္တံ၊ ပဋိက္ကမန္တု ဘူတာနိ။
သောဟံ နမော ဘဂဝတော၊ နမော သတ္တန္နံ သမ္မာသမ္ဗုဒ္ဓါနံ။` },
    ],
    translationEnglish: [
      { number: 1, text: `May I have metta towards Virupakkhas
Towards Erapathas may I have metta
May my metta be towards Chabyaputtas
Towards Kanha-gotamakas also metta may I have.` },
      { number: 2, text: `May I have metta towards the footless
And towards bipeds too, my metta may I have
May I have metta towards the quadrupeds
And towards the many footed also, metta may I have.` },
      { number: 3, text: `Let not the footless do me harm
Nor those that have two feet
Let not quadrupeds do me harm
Nor those endowed with many feet.` },
      { number: 4, text: `All beings, all living creatures,
May good fortune befall them all
May not the least harm on them befall.
"Infinite (in virtue) is the Buddha, infinite is the Dhamma, infinite is the Sangha. Finite are creeping creatures — snakes, scorpions, centipedes, spiders, lizards, and rats. I have guarded myself, I have made my protection. Depart from me, ye beings. I bow down to the Blessed One; and to the seven Supreme Buddhas."` },
    ],
    translationMyanmar: [
      { number: 1, text: `ဝိရုပက္ခတို့အား မေတ္တာပို့ပါ။
ဧရာပထတို့အား မေတ္တာပို့ပါ။
ငါ၏မေတ္တာသည် သဗျပုတ္တတို့အား မေတ္တာပို့ပါ။
ကဏဂေါတမတို့အားလည်း မေတ္တာပို့ပါ။` },
      { number: 2, text: `ခြေမရှိသူတို့အပေါ်တွင်လည်း မေတ္တာပို့ပါ။
ခြေနှစ်ချောင်းရှိသောသူတို့အပေါ်တွင်လည်း မေတ္တာပို့ပါ။
ခြေလေးချောင်းရှိသောသူတို့အပေါ်တွင်လည်း မေတ္တာပို့ပါ။
ခြေများစွာရှိသောသူတို့အပေါ်တွင်လည်း မေတ္တာပို့ပါ။` },
      { number: 3, text: `ခြေမရှိသူတို့သည် ငါ့ကို မထိခိုက်စေပါနှင့်။
ခြေနှစ်ချောင်းရှိသောသူတို့ကလည်း မထိခိုက်စေပါနှင့်။
ခြေလေးချောင်းရှိသောသူတို့ကလည်း ငါ့ကို မထိခိုက်စေပါနှင့်။
ခြေများစွာရှိသောသူတို့ကလည်း မထိခိုက်စေပါနှင့်။` },
      { number: 4, text: `သတ္တဝါအားလုံး၊ သက်ရှိသတ္တဝါအားလုံး၊
ကောင်းချီးမင်္ဂလာများသည် သူတို့အပေါ်သို့ ကျရောက်ပါစေ။
ဘေးဒုက္ခအနည်းငယ်မျှ မကျရောက်ပါစေနှင့်။
"ဗုဒ္ဓသည် အဆုံးမရှိ (သီလ၌) ရှိ၏၊ တရားသည် အဆုံးမရှိ၊ သံဃာသည် အဆုံးမရှိ၊ တွားသွားတတ်သော သတ္တဝါများဖြစ်သော မြွေ၊ ကင်းမြီးကောက်၊ ကင်းခြေများ၊ ပင့်ကူများ၊ ပုတ်သင်ညိုများနှင့် ကြွက်များသည် အဆုံးမရှိ ဖြစ်၏။ ငါသည် မိမိကိုယ်ကို စောင့်ရှောက်ပြီးပြီ၊ ငါ့ကိုယ်ငါ ကာကွယ်စောင့်ရှောက်ပြီးပြီ။ သတ္တဝါတို့၊ ငါ့ထံမှ ထွက်သွားကြလော့။ ငါသည် မြတ်စွာဘုရားကိုလည်းကောင်း၊ အနန္တတန်ခိုးရှင် ဗုဒ္ဓခုနစ်ပါးကိုလည်းကောင်း ရှိခိုးပါ၏။"` },
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
  5: {
    folderName: '05_mora_sutta',
    paliRoman: [
    ],
    paliMyanmar: [
      { number: 1, text: `ပူရေန္တံ ဗောဓိသမ္ဘာရေ၊ နိဗ္ဗတ္တံ မောရ ယောနိယံ။
ယေန သံဝိဟိတာ ရက္ခံ၊ မဟာသတ္တံ ဝနေစရာ။` },
      { number: 2, text: `စိရဿံ ဝါယမန္တာပိ၊ နေဝ သက္ခိံသု ဂဏှိတုံ။
“ဗြဟ္မမန္တ” န္တိ အက္ခာတံ၊ ပရိတ္တံ တံ ဘဏာမ ဟေ။` },
      { number: 3, text: `ဥဒေတယံ စက္ခုမာ ဧကရာဇာ၊ ဟရိဿဝဏ္ဏော ပထဝိပ္ပဘာသော။
တံ တံ နမဿမိ ဟရိဿဝဏ္ဏံ ပထဝိပ္ပ ဘာသံ၊
တယာဇ္ဇ ဂုတ္တာ ဝိဟရေမု ဒိဝသံ။` },
      { number: 4, text: `ယေ ဗြဟ္မဏာ ဝေဒဂူ သဗ္ဗဓမ္မေ၊
တေ မေ နမော တေ စ မံ ပါလယန္တု။
နမတ္ထု ဗုဒ္ဓါနံ နမတ္ထု ဗောဓိယာ၊
နမော ဝိမုတ္တာနံ နမော ဝိမုတ္တိယာ။
ဣမံ သော ပရိတ္တံ ကတွာ၊ မောရော စရတိ ဧသနာ။` },
      { number: 5, text: `အပေတယံ စက္ခုမာ ဧကရာဇာ။ ဟရိဿဝဏ္ဏော ပထဝိပ္ပဘာသော။
တံ တံ နမဿာမိ ဟရိဿဝဏ္ဏံ ပထဝိပ္ပ ဘာသံ၊
တယာဇ္ဇ ဂုတ္တာ ဝိဟရေမု ရတ္တိံ။` },
      { number: 6, text: `ယေ ဗြာဟ္မဏာ ဝေဒဂူ သဗ္ဗဓမ္မေ။
တေ မေ နမော တေစ မံ ပါလယန္တု။
နမတ္ထု ဗုဒ္ဓါနံ နမတ္ထု ဗောဓိယာ၊
နမော ဝိမုတ္တာနံ နမော ဝိမုတ္တိယာ။
ဣမံ သော ပရိတ္တံ ကတွာ၊ မောရော ဝါသ မကပ္ပယိ။
မောရသုတ္တံ နိဋ္ဌိတံ။ ။` },
    ],
    translationEnglish: [
      { number: 1, text: `There rises the golden hued one, the one who has sight, the one who is sole monarch, the one who illuminates the earth (it is the sun that is being addressed). I adore thee, the golden hued one who illuminates the earth (it is the sun that is being addressed). I adore thee, the golden hued one who illuminates the earth. Protected by thee we live this day safe and secure.` },
      { number: 2, text: `May my adoration be to those Brahmanas[2] (the Buddhas) who have attained Enlightenment by comprehending all dhammas. May they protect me. May my adoration be to the Buddhas (of the past), to their Enlightenment (the Four Paths and the Four Fruits). May my adoration be to those supremely secured from bondage (the Buddhas) and to their Deliverance. Having made this protection, the peacock goes about seeking (food).` },
      { number: 3, text: `There descends the golden hued one, the one who has sight, the one who is sole monarch, the one who illuminates the earth. I adore thee, the golden hued one who illuminates the earth. Protected by thee we live this night safe and secure.` },
      { number: 4, text: `May my adoration be to those Brahmanas (the Buddhas) who have attained Enlightenment by comprehending all dhammas. May they protect me. May my adoration be to the Buddhas (of the past), to their Enlightenment. May my adoration be to those supremely secured from bondage (the Buddhas) and to their Deliverance. Having made this protection the peacock spent his life happily.` },
    ],
    translationMyanmar: [
      { number: 1, text: `ရွှေရောင်ရှိသော အရှင်၊ မျက်စိအမြင်ရှိသော၊ တစ်ပါးတည်းသော မင်းကြီး၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော (နေမင်း) ကြွလာတော်မူ၏။ အကျွန်ုပ်သည် သင့်အား ရှိခိုးပါ၏။ ရွှေရောင်ရှိသော အရှင်၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော (နေမင်း) ကြွလာတော်မူ၏။ ရွှေရောင်ရှိသော အရှင်၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော (နေမင်း) ကြွလာတော်မူ၏။ ရွှေရောင်ရှိသော အရှင်၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော အကျွန်ုပ်သည် သင့်အား ရှိခိုးပါ၏။ အရှင်၏ စောင့်ရှောက်မှုကြောင့် ယနေ့တွင် ကျွန်ုပ်တို့သည် ဘေးကင်းလုံခြုံစွာ နေထိုင်ရပါ၏။` },
      { number: 2, text: `အလုံးစုံသော တရားတို့ကို နားလည်၍ ဉာဏ်အလင်းရရှိတော်မူသော ဗြဟ္မဏများ (ဗုဒ္ဓများ) အား အကျွန်ုပ်၏ ရိုသေလေးစားမှု ရှိပါစေ။ သူတို့သည် အကျွန်ုပ်အား စောင့်ရှောက်ကြပါစေ။ (အတိတ်ကာလက) ဗုဒ္ဓများ၊ ဉာဏ်အလင်းရရှိတော်မူသော (လမ်းလေးပါးနှင့် အသီးလေးမျိုး) အား အကျွန်ုပ်၏ ရိုသေလေးစားမှု ရှိပါစေ။ ကျွန်ဘဝမှ လွတ်မြောက်တော်မူသော (ဗုဒ္ဓများ) အား အကျွန်ုပ်၏ ရိုသေလေးစားမှု ရှိပါစေ။ ဤကာကွယ်မှုကို ပြုလုပ်ပြီးနောက် ဒေါင်းသည် (အစာ) ရှာဖွေရန် လှည့်လည်သွားလာ၏။` },
      { number: 3, text: `ရွှေရောင်ရှိသော အရှင်၊ မျက်စိအမြင်ရှိသော၊ တစ်ပါးတည်းသော မင်းကြီး၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော ထိုအရပ်သို့ ဆင်းသက်တော်မူ၏။ ရွှေရောင်ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော သင့်အား ကျွန်ုပ် ကိုးကွယ်ပါ၏။ သင့်အား ကာကွယ်စောင့်ရှောက်တော်မူခြင်းဖြင့် ဤညတွင် ဘေးကင်းလုံခြုံစွာ နေထိုင်ပါ၏။` },
      { number: 4, text: `အလုံးစုံသော ဓမ္မများကို နားလည်ခြင်းဖြင့် ဉာဏ်အလင်းရရှိတော်မူသော ဗြဟ္မဏများ (ဗုဒ္ဓများ) ကို ကျွန်ုပ်၏ ကိုးကွယ်ရာ ဖြစ်ပါစေ။ ၎င်းတို့သည် ကျွန်ုပ်ကို ကာကွယ်စောင့်ရှောက်ကြပါစေ။ (အတိတ်ကာလက) ဗုဒ္ဓများ၊ ဉာဏ်အလင်းရရှိတော်မူသော သူတို့အား ကျွန်ုပ်၏ ကိုးကွယ်ရာ ဖြစ်ပါစေ။ (ဗုဒ္ဓများ) ကျွန်ဘဝမှ လွတ်မြောက်ခြင်းနှင့် လွတ်မြောက်ခြင်းမှ အလွန်လုံခြုံတော်မူသော သူတို့အား ကျွန်ုပ်၏ ကိုးကွယ်ရာ ဖြစ်ပါစေ။ ဤအကာအကွယ်ကို ပြုလုပ်ပြီးနောက် ဒေါင်းသည် သူ၏ဘဝကို ပျော်ရွှင်စွာ ဖြတ်သန်းခဲ့သည်။` },
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
};

export default parittaContent;
