// AUTO-GENERATED by scripts/parseTexts.js
// Do not edit manually. Run: node scripts/parseTexts.js
//
// Generated: 2026-04-08T13:06:23.545Z

export interface Stanza {
  number: number;
  text: string;
}

export interface ParittaContentData {
  folderName: string;
  paliRoman: Stanza[];
  paliMyanmar: Stanza[];
  translationEnglish: Stanza[];
  translationMyanmar: Stanza[];
  preambleEnglish: string;
  preambleMyanmar: string;
}

const parittaContent: Record<number, ParittaContentData> = {
  1: {
    folderName: '01_mangala_sutta',
    paliRoman: [
      { number: 0, text: `Yaṁ maṅgalaṁ dvādasahi cintayiṁsu sadevakā,
sotthānaṁ nādhigacchanti; aṭṭhatiṁsañ-ca maṅgalaṁ
desitaṁ devadevena sabbapāpavināsanaṁ.
Sabbalokahitatthāya maṅgalaṁ parittaṁ taṁ bhaṇāmahe.

#The Safeguard` },
      { number: 1, text: `Bahū devā manussā ca maṅgalāni acintayuṃ ākankhamāna sotthānaṃ brūhi maṅgalamuttamaṃ` },
      { number: 2, text: `Asevanā ca bālānaṃ paṇḍitānañ ca sevanā pūjā ca pūjanīyānaṃ etaṃ maṅgalamuttamaṃ` },
      { number: 3, text: `Patirūpadesavāso ca pubbe ca katapuññatā attasammāpaṇidhi ca etaṃ maṅgalamuttamaṃ` },
      { number: 4, text: `Bāhusaccañ ca sippañ ca vinayo ca susikkhito subhāsitā ca yā vācā etaṃ maṅgalamuttamaṃ` },
      { number: 5, text: `Mātāpitū upatthānaṃ puttadārassa saṅgaho anākulā ca kammantā etaṃ maṅgalamuttamaṃ` },
      { number: 6, text: `Dānañ ca dhammacariyā ca ñātakānañ ca saṅgaho anavajjāni kammāni etaṃ maṅgalamuttamaṃ` },
      { number: 7, text: `ārati virati pāpā majjapānā ca saññamo appamādo ca dhammesu etaṃ maṅgalamuttamaṃ` },
      { number: 8, text: `Gāravo ca nivāto ca santuṭṭhī ca kataññutā kālena dhammasavanaṃ etaṃ maṅgalamuttamaṃ` },
      { number: 9, text: `Khantī ca sovacassatā samaṇānañ ca dassanaṃ kālena dhammasākacchā etaṃ maṅgalamuttamaṃ` },
      { number: 10, text: `Tapo ca brahmacariyañ ca ariyasaccānadassanaṃ nibbānasacchikiriyā ca etaṃ maṅgalamuttamaṃ` },
      { number: 11, text: `Phuṭṭhassa lokadhammehi cittaṃ yassa na kampati asokaṃ virajaṃ khemaṃ etaṃ maṅgalamuttamaṃ` },
      { number: 12, text: `Etādisāni katvāna sabbatthamaparājitā sabbattha sotthiṃ gacchanti taṃ tesaṃ maṅgalamuttaman’ti` },
    ],
    paliMyanmar: [
      { number: 0, text: `ဧဝံ မေ သုတံ – ဧကံ သမယံ ဘဂဝါ သာဝတ္ထိယံ ဝိဟရတိ ဇေတဝနေ အနာထပိဏ္ဍိကဿ အာရာမေ။
အထ ခေါ အညတရာ ဒေဝတာ အဘိက္ကန္တာယ ရတ္တိယာ အဘိက္ကန္တဝဏ္ဏာ ကေဝလကပ္ပံ ဇေတဝနံ ဩဘာသေတွာ ယေန ဘဂဝါ တေနုပသင်္ကမိ;
ဥပသင်္ကမိတွာ ဘဂဝန္တံ အဘိဝါဒေတွာ ဧကမန္တံ အဋ္ဌာသိ။
ဧကမန္တံ ဌိတာ ခေါ သာ ဒေဝတာ ဘဂဝန္တံ ဂါထာယ အဇ္ဈဘာသိ –` },
      { number: 1, text: `ဗဟူ ဒေဝါ မနုဿာ စ၊ မင်္ဂလာနိ အစိန္တယုံ။
အာကင်္ခမာနာ သောတ္ထာနံ၊ ဗြူဟိ မင်္ဂလမုတ္တမံ။` },
      { number: 2, text: `အသေဝနာ စ ဗာလာနံ၊ ပဏ္ဍိတာနဉ္စ သေဝနာ။
ပူဇာ စ ပူဇနေယျာနံ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 3, text: `ပတိရူပဒေသဝါသော စ၊ ပုဗ္ဗေ စ ကတပုညတာ။
အတ္တသမ္မာပဏိဓိ စ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 4, text: `ဗာဟုသစ္စဉ္စ သိပ္ပဉ္စ၊ ဝိနယော စ သုသိက္ခိတော။
သုဘာသိတာ စ ယာ ဝါစာ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 5, text: `မာတာပိတု ဥပဋ္ဌာနံ၊ ပုတ္တဒာရဿ သင်္ဂဟော။
အနာကုလာ စ ကမ္မန္တာ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 6, text: `ဒာနဉ္စ ဓမ္မစရိယာ စ၊ ဉာတကာနဉ္စ သင်္ဂဟော။
အနဝဇ္ဇာနိ ကမ္မာနိ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 7, text: `အာရတီ ဝိရတီ ပါပါ၊ မဇ္ဇပါနာ စ သံယမော။
အပ္ပမာဒော စ ဓမ္မေသု၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 8, text: `ဂါရဝေါ စ နိဝါတော စ၊ သန္တုဋ္ဌိ စ ကတညုတာ။
ကာလေန ဓမ္မဿဝနံ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 9, text: `ခန္တီ စ သောဝစဿတာ၊ သမဏာနဉ္စ ဒဿနံ။
ကာလေန ဓမ္မသာကစ္ဆာ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 10, text: `တပေါ စ ဗြဟ္မစရိယဉ္စ၊ အရိယသစ္စာန ဒဿနံ။
နိဗ္ဗာနသစ္ဆိကိရိယာ စ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 11, text: `ဖုဋ္ဌဿ လောကဓမ္မေဟိ၊ စိတ္တံ ယဿ န ကမ္ပတိ။
အသောကံ ဝိရဇံ ခေမံ၊ ဧတံ မင်္ဂလမုတ္တမံ။` },
      { number: 12, text: `ဧတာဒိသာနိ ကတွာန၊ သဗ္ဗတ္ထမပရာဇိတာ။
သဗ္ဗတ္ထ သောတ္ထိံ ဂစ္ဆန္တိ၊ တံ တေသံ မင်္ဂလမုတ္တမန္တိ။` },
    ],
    translationEnglish: [
      { number: 0, text: `What a blessing is was thought about by gods and men for twelve (years),
but they did not attain (true) safety; the thirty-eight blessings
which were preached by the god of gods make all that is bad perish.
For the whole world’s benefit and welfare we will recite that blessed safeguard.` },
      { number: 1, text: `"Many deities and men longing for happiness have pondered on (the question of) blessings. Pray tell me what the highest blessings are.` },
      { number: 2, text: `"Not to associate with the foolish, but to associate with the wise, and to honor those worthy of honor — this is the highest blessing.` },
      { number: 3, text: `"To reside in a suitable locality, to have performed meritorious actions in the past, and to set oneself in the right direction — this is the highest blessing.` },
      { number: 4, text: `"Vast learning, skill in handicrafts, well grounded in discipline, and pleasant speech — this is the highest blessing.` },
      { number: 5, text: `"To support one's father and mother; to cherish one's wife and children, and to be engaged in peaceful occupations — this is the highest blessing.` },
      { number: 6, text: `"Liberality, righteous conduct, rendering assistance to relatives, and performance of blameless deeds — this is the highest blessing.` },
      { number: 7, text: `"To cease and abstain from evil, to abstain from intoxicating drinks, and diligent in performing righteous acts — this is the highest blessing.` },
      { number: 8, text: `"Reverence, humility, contentment, gratitude, and the timely hearing of the Dhamma, the teaching of the Buddha — this is the highest blessing.` },
      { number: 9, text: `"Patience, obedience, meeting the Samanas (holy men), and timely discussions on the Dhamma — this is the highest blessing.` },
      { number: 10, text: `"Self-control, chastity, comprehension of the Noble Truths, and the realization of Nibbana — this is the highest blessing.` },
      { number: 11, text: `"The mind that is not touched by the vicissitudes of life,[2] the mind that is free from sorrow, stainless, and secure — this is the highest blessing.` },
      { number: 12, text: `"Those who have fulfilled the conditions (for such blessings) are victorious everywhere, and attain happiness everywhere — To them these are the highest blessings."` },
    ],
    translationMyanmar: [
      { number: 0, text: `ဤသည်ကား အဘယ်မင်္ဂလာနည်းဟု နတ်လူတို့ ဆယ့်နှစ်တိုင်တိုင် ကြံစည်ဆင်ခြင်ခဲ့သော်လည်း (စစ်မှန်သော) ချမ်းသာမှုကို မရနိုင်ခဲ့သည်။
နတ်တို့၏နတ်ဖြစ်တော်မူသော မြတ်စွာဘုရား ဟောကြားတော်မူအပ်သော မင်္ဂလာ (၃၈)ပါးတို့သည် မကောင်းမှုအလုံးစုံတို့ကို ကုန်စေကုန်၏။
ဤလောကတစ်ခုလုံး၏ အကျိုးစီးပွားချမ်းသာအလို့ငှာ ထိုမင်္ဂလာတရားမြတ်ကို ကျွန်ုပ်တို့ ရွတ်ဆိုကြပါမည်။` },
      { number: 1, text: `“ပျော်ရွှင်မှုကို တောင့်တသော နတ်သားနှင့် လူတို့သည် ကောင်းချီးမင်္ဂလာများကို ဆင်ခြင်သုံးသပ်ကြ၏။ အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာကား အဘယ်နည်းဟု အကျွန်ုပ်အား ပြောပြပါ။` },
      { number: 2, text: `“မိုက်မဲသောသူတို့နှင့် မပေါင်းသင်းဘဲ ပညာရှိတို့နှင့် ပေါင်းသင်းခြင်း၊ ရိုသေထိုက်သော သူတို့အား ရိုသေလေးစားခြင်းသည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာ ဖြစ်သည်။` },
      { number: 3, text: `“သင့်လျော်သော အရပ်၌ နေထိုင်ခြင်း၊ အတိတ်က ကောင်းမှုကုသိုလ်များကို ပြုလုပ်ခြင်း၊ မှန်ကန်သော လမ်းကြောင်းတွင် ရပ်တည်ခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာ ဖြစ်သည်။` },
      { number: 4, text: `“ကျယ်ပြန့်သော အသိပညာ၊ လက်မှုပညာတွင် ကျွမ်းကျင်ခြင်း၊ ကျင့်ဝတ်၌ ကောင်းစွာ ခိုင်မာခြင်း၊ သာယာသော စကားသည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာ ဖြစ်သည်။` },
      { number: 5, text: `မိဘကို ထောက်ပံ့ခြင်း၊ ဇနီးနှင့် သားသမီးများကို တန်ဖိုးထားခြင်း၊ ငြိမ်းချမ်းသော အလုပ်အကိုင်များတွင် ပါဝင်ဆောင်ရွက်ခြင်းသည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 6, text: `ရက်ရောခြင်း၊ ဖြောင့်မတ်စွာ ပြုမူခြင်း၊ ဆွေမျိုးများအား ကူညီခြင်း၊ အပြစ်ကင်းသော အကျင့်များကို ကျင့်ကြံခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 7, text: `မကောင်းမှုကို ရပ်တန့်၍ ရှောင်ကြဉ်ခြင်း၊ မူးယစ်သောက်စားခြင်းမှ ရှောင်ကြဉ်ခြင်း၊ ဖြောင့်မတ်သော အကျင့်များကို ကျင့်ကြံခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 8, text: `ရိုသေလေးစားခြင်း၊ နှိမ့်ချခြင်း၊ ကျေနပ်ခြင်း၊ ကျေးဇူးတင်ခြင်း၊ ဗုဒ္ဓ၏ တရားတော်ကို အချိန်မီ နာကြားနိုင်ခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 9, text: `သည်းခံခြင်း၊ နာခံခြင်း၊ သမဏများနှင့် တွေ့ဆုံခြင်း၊ ဓမ္မကို အချိန်မီ ဆွေးနွေးခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 10, text: `ကိုယ့်ကိုယ်ကိုယ် ထိန်းကျောင်းခြင်း၊ သီလစင်ကြယ်ခြင်း၊ အရိယာတို့၏ အမှန်တရားကို နားလည်ခြင်းနှင့် နိဗ္ဗာန်ကို မျက်မှောက်ပြုခြင်းတို့သည် အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 11, text: `"ဘဝ၏ အပြောင်းအလဲများကြောင့် မထိခိုက်သောစိတ်၊[2] ဝမ်းနည်းမှုကင်းသော၊ အညစ်အကြေးကင်းစင်သော၊ လုံခြုံသောစိတ် - ဤသည်မှာ အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာဖြစ်သည်။` },
      { number: 12, text: `"(ထိုကဲ့သို့သော ကောင်းချီးမင်္ဂလာများအတွက်) အခြေအနေများနှင့် ပြည့်စုံသူများသည် နေရာတိုင်းတွင် အောင်ပွဲခံကြပြီး နေရာတိုင်းတွင် ပျော်ရွှင်မှုကို ရရှိကြသည် - ၎င်းတို့အတွက် ဤသည်မှာ အမြင့်ဆုံးသော ကောင်းချီးမင်္ဂလာများဖြစ်သည်။"` },
    ],
    preambleEnglish: `#Prelude`,
    preambleMyanmar: ``,
  },
  2: {
    folderName: '02_ratana_sutta',
    paliRoman: [
      { number: 1, text: `Paṇidhānato paṭṭhāya, Tathāgatassa dasapāramiyo,
dasa-upapāramiyo, dasaparamatthapāramiyo ti - samatiṁsapāramiyo
pañcamahāpariccāge, lokatthacariyaṁ
ñātatthacariyaṁ Buddhatthacariyan-ti
tisso cariyāyo, pacchimabhave gabbhāvokkantiṁ, jātiṁ,
abhinikkhamanaṁ, padhānacariyaṁ, Bodhipallaṅke,
Māravijayaṁ, Dhammacakkappavattanam,
sabbaññutañāṇappaṭivedhaṁ, navalokuttaradhamme ti,
sabbe pime Buddhaguṇe āvajjitvā, Vesāliyā tīsu pākārantaresu,
tiyāmarattiṁ, parittaṁ karonto āyasmā Ānandatthero
viya kāruññacittaṁ upaṭṭhapetvā:` },
      { number: 2, text: `Koṭīsatasahassesu cakkavāḷesu devatā
Yassānaṁ paṭiggaṇhanti yañ-ca Vesāliyā pure,` },
      { number: 3, text: `rogāmanusssadubbhikkhasambhūtaṁ tividhaṁ bhayaṁ,
khippam-antaradhāpesi, parittaṁ taṁ bhaṇāmahe:` },
      { number: 4, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yā niva antaḷikkhe
Sabbeva bhūtā sumanā bhavantu
Athopi sakkacca sunantu bhāsitaṁ` },
      { number: 5, text: `Tasmā hi bhūtā nisāmetha sabbe
Mettaṁ karotha mānusiyā pajāya
Divā ca ratto ca haranti ye baliṁ
Tasmā hi ne rakkhatha appamattā` },
      { number: 6, text: `Yaṁ kiñci vittaṁ idha vā huraṁ vā
Saggesu vā yaṁ ratanaṁ paṇītaṁ
Na no samaṁ atthi Tathāgatena
Idampi Buddhe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 7, text: `Khayaṁ virāgaṁ amataṁ paṇītaṁ
Yadajjhagā Sakyamunī samāhito
Na tena Dhammena samatthi kiñci
Idampi Dhamme ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 8, text: `Yaṁ Buddhaseṭṭho parivaṇṇayī suciṁ
Samādimānantarikaññamāhu
Samādhinā tena samo na vijjati
Idampi Dhamme ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 9, text: `Ye puggalā aṭṭha sataṁ pasatthā
Cattāri etāni yugāni honti
Te dakkhiṇeyyā Sugatassa sāvakā
Etesu dinnāni mahapphalāni
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 10, text: `Ye suppayuttā manasā daḷhena
Nikkāmino Gotama sāsanamhi
Te pattipattā amataṁ vigayha
Laddhā mudhā nibbutiṁ bhuñjamānā
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 11, text: `Yathindakhīlo paṭhaviṁ sito siyā
Catubbhi vātebhi asampakampiyo
Tathūpamaṁ sappurisaṁ vadāmi
Yo ariyasaccāni avecca passati
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 12, text: `Ye ariyasaccāni vibhāvayanti
Gambhīrapaññena sudesitāni
Kiñcāpi te honti bhusappamattā
Na te bhavaṁ aṭṭhamaṁ ādiyanti
Idam’pi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 13, text: `Sahāva’ssa dassana sampadāya
Tayassu dhammā jahitā bhavanti
Sakkāyadiṭṭhi vicikicchitañ ca
Sīlabbataṁvā’pi yadatthi kiñci
Catūhapāyehi ca vippamutto,
Cha cābhiṭhānāni abhabbo kātuṁ
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 14, text: `Kiñcā’pi so kammaṁ karoti pāpakaṁ
Kāyena vācā uda cetasā vā
Abhabbo so tassa paṭicchādāya
Abhabbatā diṭṭha padassa vuttā
Idampi Saṅghe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 15, text: `Vanappagumbe yathā phussitagge
Gimhānamāse paṭhamasmiṁ gimhe
Tathūpamaṁ Dhamma varaṁ adesayi
Nibbāṇagāmiṁ paramaṁ hitāya
Idampi Buddhe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 16, text: `Varo varaññū varado varāharo
Anuttaro Dhamma varaṁ adesayi
Idampi Buddhe ratanaṁ paṇītaṁ
Etena saccena suvatthi hotu` },
      { number: 17, text: `Khīṇaṁ purāṇaṁ navaṁ natthi sambhavaṁ
virattacittā āyatike bhavasmiṁ
Te khīṇabījā avirūḷhicchandā
Nibbanti dhīrā yathāyaṁ padīpo
Idampi Saṅghe ratanaṁ paṇītaṁ,
Etena saccena suvatthi hotu` },
      { number: 18, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yāniva antaḷikkhe
Tathāgataṁ devamanussa pūjitaṁ
Buddhaṁ namassāma suvatthi hotu` },
      { number: 19, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yāniva antaḷikkhe
Tathāgataṁ devamanussa pūjitaṁ
Dhammaṁ namassāma suvatthi hotu` },
      { number: 20, text: `Yānīdha bhūtāni samāgatāni
Bhummāni vā yāniva antaḷikkhe
Tathāgataṁ devamanussa pūjitaṁ
Saṅghaṁ namassāma suvatthi hotu` },
    ],
    paliMyanmar: [
      { number: 1, text: `ပဏိဓာနတော ပဋ္ဌာယ တထာ ဂတဿ ဒသ ပါရမိယော,
ဒသ ဥပပါရမိယော, ဒသ ပရမတ္ထ ပါရမိယောတိ
သမတ္တိံသ ပါရမိယော, ပဉ္စ မဟာပရိစ္စာဂေ,
လောကတ္ထစရိယံ ဉာတတ္ထစရိယံ
ဗုဒ္ဓတ္ထစရိယန္တိ တိဿော စရိယာယော၊
ပစ္ဆိမဘဝေ ဂဗ္ဘဝေါက္ကန္တိံ၊ ဇာတိံ အဘိနိက္ခမနံ၊
ပဓာနစရိယံ ဗောဓိပလ္လင်္ကေ မာရဝိဇယံ သဗ္ဗညုတညာဏပ္ပဋိဝေဓံ။
ဓမ္မစက္ကပ္ပဝတ္တနံ, နဝ လောကုတ္တရ ဓမ္မေတိ၊ သဗ္ဗေပိ မေ ဗုဒ္ဓဂုဏေ၊
အာဝဇ္ဇေ တွာ ဝေသာ လိယာ တီသု ပါကာရန္တ ရေသု
တိယာမရတ္တိံ ပရိတ္တံ ကရောန္တော အာယသ္မာ အာနန္ဒတ္ထေ ရောဝိယ၊
ကာရုညစိတ္တံ ဥပဋ္ဌပေတွာ —` },
      { number: 2, text: `ကောဋီသတသဟဿေသု၊ စက္ကဝါဠေသု ဒေဝတာ။
ယဿာဏံ ပဋိဂ္ဂဏှန္တိ၊ ယဉ္စ ဝေသာလိယာ ပုရေ။` },
      { number: 3, text: `ရောဂါမနုဿဒုဗ္ဘိက္ခ−သမ္ဘူတံ တိဝိဓံ ဘယံ။
ခိပ္ပ မန္တရဓာပေသိ၊ ပရိတ္တံ တံ ဘဏာမဟေ။` },
      { number: 4, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိ ဝ အန္တလိက္ခေ။
သဗ္ဗေဝ ဘူတာ သုမနာ ဘဝန္တု၊
အထောပိ သက္ကစ္စ သုဏန္တု ဘာသိတံ။` },
      { number: 5, text: `တသ္မာဟိ ဘူတာ နိသာမေထ သဗ္ဗေ၊
မေတ္တံ ကရောထ မာနုသိယာ ပဇာယ။
ဒိဝါ စ ရတ္တော စ ဟရန္တိ ယေ ဗလိံ၊
တသ္မာ ဟိ နေ ရက္ခထ အပ္ပမတ္တာ။` },
      { number: 6, text: `ယံကိဉ္စိ ဝိတ္တံ ဣဓ ဝါ ဟုရံ ဝါ၊
သဂ္ဂေသု ဝါ ယံ ရတနံ ပဏီတံ၊
န နော သမံ အတ္ထိ တထာဂတေန၊
ဣဒမ္ပိ ဗုဒ္ဓေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 7, text: `ခယံ ဝိရာဂံ အမတံ ပဏီတံ၊
ယဒဇ္ဈ ဂါ သကျမုနီ သမာဟိတော။
န တေန ဓမ္မေန သမတ္ထိ ကိဉ္စိ၊
ဣဒမ္ပိ ဓမ္မေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 8, text: `ယံ ဗုဒ္ဓသေဋ္ဌော ပရိဝဏ္ဏယီ သုစိံ၊
သမာဓိ မာနန္တရိက ည မာဟု။
သမာဓိနာ တေန သမော န ဝိဇ္ဇတိ၊
ဣဒမ္ပိ ဓမ္မေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 9, text: `ယေ ပုဂ္ဂလာ အဋ္ဌ သတံ ပသတ္ထာ၊
စတ္တာရိ ဧတာနိ ယုဂါနိ ဟောန္တိ။
တေ ဒက္ခိဏေယျာ သုဂတဿ သာဝကာ၊
ဧတေသု ဒိန္နာနိ မဟပ္ဖလာနိ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္တိ ဟောတု။` },
      { number: 10, text: `ယေ သုပ္ပယုတ္တာ မနသာ ဒဠှေန၊
နိက္ကာ မိနော ဂေါတမသာသနမှိ။
တေ ပတ္တိပတ္တာ အမတံ ဝိဂယှ၊
လဒ္ဓါ မုဓာ နိဗ္ဗုတိံ ဘုဉ္ဇ မာနာ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 11, text: `ယထိန္ဒခီလော ပထဝိဿိတော သိယာ၊
စတုဗ္ဘိ ဝါတေဟိ အသမ္ပကမ္ပိယော။
တထူပမံ သပ္ပုရိသံ ဝဒါမိ။
ယော အရိယသစ္စာနိ အဝေစ္စ ပဿတိ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 12, text: `ယေအရိယ သစ္စာနိ ဝိဘာဝယန္တိ၊
ဂမ္ဘီရပညေန သုဒေသိတာနိ။
ကိဉ္စာပိ တေ ဟောန္တိ ဘုသံ ပမတ္တာ၊
န တေ ဘဝံ အဋ္ဌမ မာဒိယန္တိ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 13, text: `သဟာဝဿ ဒဿန သမ္ပဒါယ၊
တယဿု ဓမ္မာ ဇဟိတာ ဘဝန္တိ။
သက္ကာယဒိဋ္ဌီ ဝိစိကိစ္ဆိတဉ္စ၊
သီလဗ္ဗတံ ဝါပိ  ယဒတ္ထိ ကိဉ္စိ။
စတူဟပါယေဟိ စ ဝိပ္ပမုတ္တော၊
ဆစ္စာဘိဌာနာနိ အဘဗ္ဗ ကာတုံ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 14, text: `ကိဉ္စာပိ သော ကမ္မကရောတိ ပါပကံ၊
ကာယေန ဝါစာ ဥဒ စေတသာ ဝါ၊
အဘဗ္ဗ သော တဿ ပဋိစ္ဆဒါယ၊
အဘဗ္ဗတာ ဒိဋ္ဌပဒဿာ ဝုတ္တာ၊
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ။
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 15, text: `ဝနပ္ပဂုမ္ဗေ ယထ ဖုဿိတဂ္ဂေ၊
ဂိမှာန မာသေ ပဌမသ္မိံ ဂိမှေ။
တထူပမံ ဓမ္မဝရံ အဒေသယိ၊
နိဗ္ဗာနဂါမိံ ပရမံ ဟိတာယ။
ဣဒမ္ပိ ဗုဒ္ဓေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 16, text: `ဝရော ဝရညူ ဝရဒေါ ဝရာဟရော၊
အနုတ္တရော ဓမ္မဝရံ အဒေသယိ။
ဣဒမ္ပိ ဗုဒ္ဓေ ရတနံ ပဏီတံ။
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 17, text: `ခီဏံ ပုရာဏံ နာဝ နတ္ထိ သမ္ဘဝံ၊
ဝိရတ္တစိတ္တာယတိကေ ဘဝသ္မိံ။
တေ ခီဏဗီဇာ အဝိရူဠိဆန္ဒာ၊
နိဗ္ဗန္တိ ဓီရာ ယထာယံ ပဒီပေါ။
ဣဒမ္ပိ သံဃေ ရတနံ ပဏီတံ၊
ဧတေန သစ္စေန သုဝတ္ထိ ဟောတု။` },
      { number: 18, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိ ဝ အန္တ လိက္ခေ။
တထာဂတံ ဒေဝမနုဿ ပူဇိတံ၊
ဗုဒ္ဓံ နမဿာမ သုဝတ္ထိ ဟောတု။` },
      { number: 19, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိဝ အန္တ လိက္ခေ။
တထာဂတံ ဒေဝမနုဿပူဇိတံ၊
ဓမ္မံ နမဿာမ သုဝတ္ထိ ဟောတု။` },
      { number: 20, text: `ယာနီဓ ဘူတာနိ သမာဂတာနိ၊
ဘုမ္မာနိ ဝါ ယာနိ ဝ အန္တ လိက္ခေ။
တထာဂတံ ဒေဝမနုဿ ပူဇိတံ၊
သံဃံ နမဿာမ သုဝတ္ထိ ဟောတု။` },
    ],
    translationEnglish: [
      { number: 1, text: `Beginning with the aspiration (for Buddhahood, and thinking of) the Realised One’s ten perfections,
ten minor perfections, ten great perfections - altogether thirty perfections,
his five great sacrifices, life of benefitting the world, life of benefitting his relatives, life of benefitting (by becoming) Buddha,
life of benefitting his relatives, life of benefitting (by becoming) Buddha,
three ways of conduct, descent into the womb for his final existence, birth,
great renunciation, life of effort, sitting cross legged at the Bodhi tree,
victory over Māra, turning of the Wheel of Dhamma,
his penetration and knowledge of omniscience, and his nine supermundane attainments,
and after considering all these Buddha qualities, (going around) the three walls of Vesāli,
during the three watches of the night, the venerable elder Ānanda,
after establishing great compassion in his heart, made this safeguard:` },
      { number: 2, text: `The gods in the ten hundred thousand million universes
accepted the order (given) in the city of Vesāli,` },
      { number: 3, text: `and disease, non-human beings, and famine, the threefold fear that had arisen,
quickly disappeared, we will recite that safeguard:` },
      { number: 4, text: `"Whatever beings (non-humans) are assembled here, terrestrial or celestial, may they all have peace of mind, and may they listen attentively to these words."` },
      { number: 5, text: `"O beings, listen closely. May you all radiate loving-kindness to those human beings who, by day and night, bring offerings to you (offer merit to you). Wherefore, protect them with diligence."` },
      { number: 6, text: `"Whatever treasure there be either in the world beyond, whatever precious jewel there be in the heavenly worlds, there is nought comparable to the Tathagata (the perfect One). This precious jewel is the Buddha.[4] By this (asseveration of the) truth may there be happiness."` },
      { number: 7, text: `"That Cessation, that Detachment, that Deathlessness (Nibbana) supreme, the calm and collected Sakyan Sage (the Buddha) had realized. There is nought comparable to this (Nibbana) Dhamma. This precious jewel is the Dhamma.[5] By this (asseveration of the) truth may there be happiness."` },
      { number: 8, text: `"The Supreme Buddha extolled a path of purity (the Noble Eightfold Path) calling it the path which unfailingly brings concentration. There is nought comparable to this concentration. This precious jewel is the Dhamma. By this (asseveration of the) truth may there be happiness."` },
      { number: 9, text: `"The eight persons extolled by virtuous men constitute four pairs. They are the disciples of the Buddha and are worthy of offerings. Gifts given to them yield rich results. This precious jewel is the Sangha.[6] By this (asseveration of the) truth may there be happiness."` },
      { number: 10, text: `"With a steadfast mind, and applying themselves well in the dispensation of the Buddha Gotama, free from (defilements), they have attained to that which should be attained (arahantship) encountering the Deathless. They enjoy the Peace of Nibbana freely obtained.[7] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 11, text: `"As a post deep-planted in the earth stands unshaken by the winds from the four quarters, so, too, I declare is the righteous man who comprehends with wisdom the Noble Truths. This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 12, text: `"Those who realized the Noble Truths well taught by him who is profound in wisdom (the Buddha), even though they may be exceedingly heedless, they will not take an eighth existence (in the realm of sense spheres).[8] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 13, text: `"With his gaining of insight he abandons three states of mind, namely self-illusion, doubt, and indulgence in meaningless rites and rituals, should there be any. He is also fully freed from the four states of woe, and therefore, incapable of committing the six major wrongdoings.[9] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 14, text: `"Any evil action he may still do by deed, word or thought, he is incapable of concealing it; since it has been proclaimed that such concealing is impossible for one who has seen the Path (of Nibbana).[10] This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 15, text: `"As the woodland groves though in the early heat of the summer month are crowned with blossoming flowers even so is the sublime Dhamma leading to the (calm) of Nibbana which is taught (by the Buddha) for the highest good. This precious jewel is the Buddha. By this (asseveration of the) truth may there be happiness."` },
      { number: 16, text: `"The Peerless Excellent one (the Buddha) the Knower (of Nibbana), the Giver (of Nibbana), the Bringer (of the Noble Path), taught the excellent Dhamma. This precious jewel is the Buddha. By this (asseveration of the) truth may there be happiness."` },
      { number: 17, text: `"Their past (kamma) is spent, their new (kamma) no more arises, their mind to future becoming is unattached. Their germ (of rebirth-consciousness) has died, they have no more desire for re-living. Those wise men fade out (of existence) as the flame of this lamp (which has just faded away). This precious jewel is the Sangha. By this (asseveration of the) truth may there be happiness."` },
      { number: 18, text: `"Whatever beings are assembled here, terrestrial or celestial, come let us salute the Buddha, the Tathagata, honored by gods and men. May there be happiness."` },
      { number: 19, text: `"Whatever beings are assembled here terrestrial or celestial, come let us salute the perfect Dhamma, honored by gods and men. May there be happiness."` },
      { number: 20, text: `"Whatever beings are assembled here terrestrial or celestial, come let us salute the perfect Sangha, honored by gods and men. May there be happiness."` },
    ],
    translationMyanmar: [
      { number: 1, text: `ဤတရားဒေသနာတော်အတွက် အကျဉ်းချုပ်ပြောရလျှင် အဋ္ဌကထာအရ အောက်ပါအတိုင်းဖြစ်သည်- ဝေသာလီမြို့သည် အစာရေစာငတ်မွတ်ခေါင်းပါးမှုဒဏ်ကို ခံခဲ့ရပြီး အထူးသဖြင့် ဆင်းရဲသားများအား သေဆုံးစေခဲ့သည်။ ပုပ်သိုးနေသော အလောင်းများရှိနေခြင်းကြောင့် မကောင်းဆိုးဝါးဝိညာဉ်များသည် မြို့ကို ခြောက်လှန့်လာခဲ့ပြီး ထို့နောက် ကပ်ရောဂါဘေးကြီး ကျရောက်ခဲ့သည်။ အစာရေစာငတ်မွတ်ခေါင်းပါးမှု၊ လူမဟုတ်သူများနှင့် ကပ်ရောဂါဘေးဟူသော ဤကြောက်ရွံ့မှုသုံးမျိုးကြောင့် မြို့သူမြို့သားများသည် ရာဇဂြိုဟ်တွင် နေထိုင်သော ဗုဒ္ဓ၏အကူအညီကို ရှာဖွေခဲ့ကြသည်။` },
      { number: 2, text: `နောက်တော်ပါ တပည့်ဖြစ်သူ အရှင်အာနန္ဒာအပါအဝင် ရဟန်းအမြောက်အမြား လိုက်ပါလာပြီး ဗုဒ္ဓသည် ဝေသာလီမြို့သို့ ကြွရောက်ခဲ့သည်။ အရှင်ဘုရားကြွလာသောအခါ မိုးသည်းထန်စွာရွာသွန်းပြီး ပုပ်သိုးနေသော အလောင်းများကို သယ်ဆောင်သွားခဲ့သည်။ လေထုသည် သန့်စင်လာပြီး မြို့သည် သန့်ရှင်းလာသည်။` },
      { number: 3, text: `ထို့နောက် ဗုဒ္ဓသည် ဤရတနာတရားဒေသနာ (ရတနာသုတ္တန်[2]) ကို အရှင်အာနန္ဒာအား ဟောကြားခဲ့ပြီး ဝေသာလီမြို့သားများအား ကာကွယ်စောင့်ရှောက်သည့်အနေဖြင့် တရားဒေသနာတော်ကို ရွတ်ဆိုနေသော လိစ္ဆဝီမြို့သားများနှင့်အတူ မြို့တွင်း မည်သို့လှည့်လည်ရမည်ကို ညွှန်ကြားခဲ့သည်။ အရှင်အာနန္ဒာသည် ညွှန်ကြားချက်များကို လိုက်နာပြီး ဗုဒ္ဓ၏ ဆွမ်းခံသပိတ်မှ သန့်ရှင်းသောရေကို ပက်ဖျန်းခဲ့သည်။ ထို့ကြောင့် မကောင်းဆိုးဝါးနတ်ဆိုးများ နှင်ထုတ်ခံရပြီး ကပ်ရောဂါလည်း ငြိမ်သက်သွားခဲ့သည်။ ထို့နောက် အရှင်အာနန္ဒာသည် ဝေသာလီမြို့သူမြို့သားများနှင့်အတူ ဗုဒ္ဓနှင့် တပည့်များ စုဝေးရောက်ရှိရန် စုဝေးခဲ့ကြသည့် အများပြည်သူခန်းမသို့ ပြန်လာခဲ့သည်။ ထိုနေရာတွင် ဗုဒ္ဓသည် ထိုရတနာတရားတော်ကို စုဝေးသူများအား ဟောကြားခဲ့သည်- [၃]` },
      { number: 4, text: `“မြေကြီးဖြစ်စေ၊ ကောင်းကင်ဖြစ်စေ ဤနေရာတွင် စုဝေးနေသော သတ္တဝါအားလုံး စိတ်၏ချမ်းသာမှုကို ရရှိကြပါစေ၊ ဤစကားများကို အာရုံစိုက် နားထောင်နိုင်ကြပါစေ။` },
      { number: 5, text: `“အို သတ္တဝါတို့၊ သေချာစွာ နားထောင်ကြလော့။ နေ့ရောညပါ သင်တို့အား ပူဇော်သက္ကာများ ယူဆောင်လာသူများ (သင်တို့အား ကုသိုလ်များ ပေးဆောင်ကြလော့)၊ ထို့ကြောင့် သင်တို့အား ဂရုတစိုက် ကာကွယ်စောင့်ရှောက်ကြလော့။` },
      { number: 6, text: `"တမလွန်လောက၌ ရတနာတစ်စုံတစ်ရာရှိပါစေ၊ နတ်ပြည်၌ ရတနာတစ်စုံတစ်ရာရှိပါစေ၊ တထာဂတ (ပြီးပြည့်စုံသော) ပုဂ္ဂိုလ်နှင့် နှိုင်းယှဉ်၍မရပါ။ ဤရတနာသည် ဗုဒ္ဓဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ကြောင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 7, text: `"ထိုချုပ်ငြိမ်းခြင်း၊ ထိုကင်းကွာခြင်း၊ ထိုသေခြင်း (နိဗ္ဗာန်) သည် မြင့်မြတ်သော၊ ငြိမ်သက်ပြီး စုစည်းထားသော သကျသာကီဝင်မင်း (ဗုဒ္ဓ) သိမြင်တော်မူသော ချမ်းသာသုခ။ ဤ (နိဗ္ဗာန်) ဓမ္မနှင့် နှိုင်းယှဉ်၍မရပါ။ ဤရတနာသည် ဓမ္မဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ကြောင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 8, text: `"အမြင့်မြတ်ဆုံးသော ဗုဒ္ဓသည် ဖြူစင်သော လမ်းစဉ် (အရိယာရှစ်ပါး) ကို ချီးမြှောက်တော်မူပြီး မပြတ်တည်တံ့သော လမ်းစဉ်ကို ခေါ်ဆို၍ သမာဓိကို ဆောင်ကြဉ်းပေးသည်။ ဤသမာဓိနှင့် နှိုင်းယှဉ်၍မရပါ။ ဤရတနာသည် ဓမ္မဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ကြောင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 9, text: `"သီလရှိသော ပုဂ္ဂိုလ်ရှစ်ဦးသည် လေးစုံဖြစ်သည်။ ၎င်းတို့သည် ဗုဒ္ဓ၏ တပည့်များဖြစ်ပြီး ပူဇော်ထိုက်သူများ ဖြစ်ကြသည်။" သူတို့အားပေးသော အလှူဒါနများသည် ကြွယ်ဝသော အကျိုးကျေးဇူးများကို ရရှိစေပါသည်။ ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 10, text: `“တည်ကြည်သောစိတ်ဖြင့် ဂေါတမဗုဒ္ဓ၏ သာသနာတော်တွင် ကောင်းစွာ ကြိုးစားအားထုတ်၍ (ကိလေသာမှ ကင်းစင်) ရသင့်ရထိုက်သော အရဟတ္တမဘုံသို့ ရောက်ရှိကြပြီး မသေနိုင်သော နိဗ္ဗာန်ကို တွေ့ကြုံခံစားကြသည်။” ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 11, text: `“မြေကြီး၌ နက်ရှိုင်းစွာ စိုက်ထားသော တိုင်သည် အရပ်လေးမျက်နှာမှ လေတိုက်ခတ်မှုဒဏ် မခံရသကဲ့သို့၊ ဉာဏ်ပညာဖြင့် အရိယာသစ္စာတရားကို နားလည်သော သူတော်ကောင်းလည်း ဖြစ်သည်ဟု ငါ မိန့်ကြား၏။ ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) ဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 12, text: `"ဉာဏ်ပညာနှင့်ပြည့်စုံတော်မူသော (ဗုဒ္ဓ) ကောင်းစွာ ဟောကြားတော်မူသော အရိယာသစ္စာတရားများကို သဘောပေါက်သူတို့သည် အလွန်သတိမဲ့နေသော်လည်း (အာရုံငါးပါးတွင်) ရှစ်ပါးသောဘဝသို့ မရောက်နိုင်ကြပေ။" [၈] ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို) သိမြင်ခြင်းဖြင့် ပျော်ရွှင်မှု ရှိပါစေ။` },
      { number: 13, text: `"ဉာဏ်အမြင်ရရှိခြင်းဖြင့် စိတ်အခြေအနေသုံးမျိုးကို စွန့်လွှတ်သည်။ ၎င်းမှာ မိမိကိုယ်ကိုယ် အထင်မှားခြင်း၊ သံသယနှင့် အဓိပ္ပာယ်မရှိသော ထုံးတမ်းစဉ်လာများတွင် နစ်မွန်းခြင်း ဖြစ်သည်။ သူသည် ဆင်းရဲဒုက္ခလေးမျိုးမှလည်း လုံးဝလွတ်မြောက်ပြီး ထို့ကြောင့် အဓိကအမှားခြောက်မျိုးကို ကျူးလွန်နိုင်ခြင်းမရှိပေ။" [၉] ဤအဖိုးတန်ရတနာသည် သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို) သိမြင်ခြင်းဖြင့် ပျော်ရွှင်မှု ရှိပါစေ။` },
      { number: 14, text: `"သူသည် လုပ်ရပ်၊ စကား သို့မဟုတ် အတွေးဖြင့် မကောင်းမှုကို ပြုလုပ်နေသေးပါက၊ ၎င်းကို ဖုံးကွယ်၍မရပါ။ နိဗ္ဗာန်လမ်းကို မြင်တွေ့ပြီးသူအတွက် ထိုသို့ဖုံးကွယ်ခြင်းသည် မဖြစ်နိုင်ဟု ကြေငြာထားသောကြောင့်ဖြစ်သည်။" [၁၀] ဤအဖိုးတန်ရတနာမှာ သံဃာဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) အားဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 15, text: `"နွေရာသီ၏ အပူရှိန်တွင် တောအုပ်များသည် ပွင့်လန်းသော ပန်းများဖြင့် ဖုံးလွှမ်းနေသကဲ့သို့၊ မြတ်သောအကျိုးအတွက် (ဗုဒ္ဓ) ဟောကြားတော်မူသော နိဗ္ဗာန်၏ (ငြိမ်သက်ခြင်း) သို့ ပို့ဆောင်ပေးသော မြင့်မြတ်သောတရားလည်း ရှိပါသည်။ ဤအဖိုးတန်ရတနာမှာ ဗုဒ္ဓဖြစ်သည်။ ဤ (သစ္စာတရားကို ဟောကြားခြင်း) အားဖြင့် ချမ်းသာသုခ ရှိပါစေ။` },
      { number: 16, text: `"တုနှိုင်းမဲ့သော မြတ်သော (ဗုဒ္ဓ)၊ (နိဗ္ဗာန်ကို သိတော်မူသော)၊ (နိဗ္ဗာန်ကို ပေးသနားတော်မူသော)၊ (မြတ်သောလမ်းကို ဆောင်တော်မူသော)၊ မြတ်သောတရားကို ဟောကြားတော်မူခြင်း"` },
      { number: 17, text: `"သူတို့၏ အတိတ် (ကံ) ကုန်ဆုံးသွားပါပြီ၊ သူတို့၏ အသစ် (ကံ) မဖြစ်ပေါ်တော့ပါ၊ အနာဂတ်ဘဝအတွက် သူတို့၏ စိတ်သည် မတွယ်တာတော့ပါ။ သူတို့၏ ပဋိသန္ဓေစိတ် (ပဋိသန္ဓေစိတ်) သေသွားပါပြီ၊ သူတို့သည် ပြန်လည်ရှင်သန်လိုသော ဆန္ဒ မရှိတော့ပါ။ ထိုပညာရှိတို့သည် (ယခုမှ မှေးမှိန်သွားသော) ဤမီးခွက်၏ မီးလျှံကဲ့သို့ ပျောက်ကွယ်သွားပါသည်။ ဤအဖိုးတန်ရတနာသည် သံဃာတော်ဖြစ်သည်။ ဤ (သစ္စာတရားကို) ဖြင့် ပျော်ရွှင်မှု ရှိပါစေ။"` },
      { number: 18, text: `"ဤနေရာ၌ စုဝေးနေသော သတ္တဝါအားလုံး၊ နတ်နှင့်လူတို့ ရိုသေလေးစားခံရသော တထာဂတ ဗုဒ္ဓကို လာ၍ ရှိခိုးကြကုန်အံ့။ ပျော်ရွှင်မှု ရှိပါစေ။"` },
      { number: 19, text: `"ဤနေရာ၌ စုဝေးနေသော သတ္တဝါအားလုံး၊ နတ်နှင့်လူတို့ ရိုသေလေးစားခံရသော ပြီးပြည့်စုံသော တရားကို လာ၍ ရှိခိုးကြကုန်အံ့။ ပျော်ရွှင်မှု ရှိပါစေ။"` },
      { number: 20, text: `"ဤနေရာ၌ စုဝေးနေသော သတ္တဝါအားလုံး၊ နတ်နှင့်လူတို့ ရိုသေလေးစားခံရသော ပြီးပြည့်စုံသော သံဃာတော်ကို လာ၍ ရှိခိုးကြကုန်အံ့။ ပျော်ရွှင်မှု ရှိပါစေ။"` },
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
  3: {
    folderName: '03_metta_sutta',
    paliRoman: [
      { number: 0, text: `Yassānubhāvato yakkhā neva dassenti bhīsanaṁ,
yamhi cevānuyuñjanto rattindivam-antandito
sukhaṁ supati sutto ca pāpaṁ kiñci na passati -
evam-ādiguṇopetaṁ, parittaṁ taṁ bhaṇāmahe.` },
      { number: 1, text: `Karaṇīyam-atthakusalena, yan-ta’ santaṁ padaṁ abhisamecca:
sakko ujū ca suhujū ca, suvaco cassa mudu anatimānī,` },
      { number: 2, text: `santussako ca subharo ca, appakicco ca sallahukavutti,
santindriyo ca nipako ca, appagabbho kulesvananugiddho,` },
      { number: 3, text: `na ca khuddam-ācare kiñci yena viññū pare upavadeyyuṁ.
“Sukhino va khemino hontu, sabbasattā bhavantu sukhitattā!` },
      { number: 4, text: `Ye keci pāṇabhūtatthi tasā vā thāvarā v’ anavasesā,
dīghā vā yeva mahantā, majjhimā rassakā aṇukathūlā,` },
      { number: 5, text: `diṭṭhā vā ye va adiṭṭhā, ye va dūre vasanti avidūre,
bhūtā va sambhavesī vā sabbasattā bhavantu sukhitattā!”` },
      { number: 6, text: `Na paro paraṁ nikubbetha, nātimaññetha katthaci na’ kañci,
byārosanā paṭighasaññā nāññam-aññassa dukkham-iccheyya.` },
      { number: 7, text: `Mātā yathā niyaṁ puttam-āyusā ekaputtam-anurakkhe,
evam-pi sabbabhūtesu mānasaṁ bhāvaye aparimāṇaṁ.` },
      { number: 8, text: `Mettañ-ca sabbalokasmi’ mānasaṁ bhāvaye aparimāṇaṁ,
uddhaṁ adho ca tiriyañ-ca, asambādhaṁ averam-asapattaṁ.` },
      { number: 9, text: `Tiṭṭhaṁ caraṁ nisinno va, sayāno vā yāvatassa vitamiddho,
etaṁ satiṁ adhiṭṭheyya, brahmam-etaṁ vihāram-idha-m-āhu.` },
      { number: 10, text: `Diṭṭhiñ-ca anupaggamma, sīlavā dassanena sampanno,
kāmesu vineyya gedhaṁ, na hi jātuggabbhaseyya’ punar-eti.` },
    ],
    paliMyanmar: [
      { number: 0, text: `ယဿာနုဘာဝတော ယက္ဓာ၊ နေဝ ဒေဿေန္တိ ဘီသနံ။
ယဉှိ  စေဝါနုယုဉ္ဇန္တော၊ ရတ္တိန္ဒိဝ မတန္ဒိတော။
သုခံ သုပတိ သုတ္တော စ၊ ပါပံ ကိဉ္စိ န ပဿတိ။
ဧဝမာဒိဂုဏူပေတံ၊ ပရိတ္တံ တံ ဘဏာမ ဟေ။` },
      { number: 1, text: `ကရဏီယ’ မတ္ထ ကုသလေန၊ ယန္တ သန္တံ ပဒံ အဘိသမေစ္စ။
သက္ကော ဥဇူ စ သုဟုဇူ စ၊ သုဝစော စဿ မုဒု အနတိ မာနီ။` },
      { number: 2, text: `သန္တုဿကော စ သုဘရော စ၊ အပ္ပကိစ္စော စ သလ္လဟုကဝုတ္တိ။
သန္တိန္ဒြိယော စ နိပကောစ၊ အပ္ပဂဗ္ဘော ကုလေသွ’ နနုဂိဒ္ဓေါ။` },
      { number: 3, text: `န စ ခုဒ္ဒ’မာစရေ ကိဉ္စိ၊ ယေန ဝိညူ ပရေ ဥပဝဒေယျုံ။
သုခိနော ဝ ခေမိနော ဟောန္တု၊ သဗ္ဗသတ္တာ ဘဝန္တု သုခိတတ္တာ။` },
      { number: 4, text: `ယေ ကေစိ ပါဏဘူတတ္ထိ၊ တသာ ဝါ ထာဝရာဝ’ နဝသေသာ။
ဒီဃာ ဝါ ယေဝ မဟန္တာ၊ မဇ္ဈိမာ ရဿကာ အဏုကထူလာ။` },
      { number: 5, text: `ဒိဋ္ဌာ ဝါ ယေဝ အဒိဋ္ဌာ၊ ယေ ဝ ဒူရေ ဝသန္တိ အဝိဒူရေ။
ဘူတာ ဝ သမ္ဘဝေသီ ဝ၊ သဗ္ဗသတ္တာ ဘဝန္တု သုခိတတ္တာ။` },
      { number: 6, text: `န ပရော ပရံ နိကုဗ္ဗေထ၊ နာတိမညေထ ကတ္ထစိ နကိဉ္စိ။
ဗျာရောသနာ ပဋိဃသည၊ နာညမညဿ ဒုက္ခ မိစ္ဆေယျ။` },
      { number: 7, text: `မာတာ ယထာ နိယံ ပုတ္တ၊ မာယုသာ ဧကပုတ္တ’ မနုရက္ခေ။
ဧဝမ္ပိ သဗ္ဗဘူတေသု၊ မာနသံ ဘာဝယေ အပရိမာဏံ။` },
      { number: 8, text: `မေတ္တဉ္စ သဗ္ဗလောကသ္မိ၊ မာနသံ ဘာဝယေ အပရိမာဏံ။
ဥဒ္ဓံ အဓော စ တိရီယဉ္စ၊ အသမ္ဗာဓံ အဝေရ’ မသပတ္တံ။` },
      { number: 9, text: `တိဋ္ဌံ စရံ နိသိန္နော ဝ၊ သယာနော ယာဝတာ’ဿ ဝိတမိဒ္ဓေါ။
ဧတံ သတိံ အဓိဋ္ဌေယျ၊ ဗြဟ္မ မေတံ ဝိဟာရ မိဓ မာဟု။` },
      { number: 10, text: `ဒိဋ္ဌိဉ္စ အနုပဂ္ဂမ္မ၊ သီလဝါ ဒဿနေန သမ္ပန္နော။
ကာမေသု ဝိနေယျ ဂေဓံ၊ နဟိ ဇာတု’ဂ္ဂဗ္ဘသေယျ ပုန ရေတိ။` },
    ],
    translationEnglish: [
      { number: 0, text: `Because of the power of that (safeguard) the yakkhas could not make fearful (sights) appear,
by practising that diligently night and day
he sleeps happily, and while sleeping does not see anything bad -
it is endowed with such qualities, we will recite that safeguard.` },
      { number: 1, text: `He who is skilled in (working out his own) well being, and who wishes to attain that state of Calm (Nibbana) should act thus: he should be dexterous, upright, exceedingly upright, obedient, gentle, and humble.` },
      { number: 2, text: `Contented, easily supportable, with but few responsibilities, of simple livelihood, controlled in the senses, prudent, courteous, and not hanker after association with families.` },
      { number: 3, text: `Let him not perform the slightest wrong for which wise men may rebuke him. (Let him think:) 'May all beings be happy and safe. May they have happy minds.'` },
      { number: 4, text: `Whatever living beings there may be — feeble or strong (or the seekers and the attained) long, stout, or of medium size, short, small, large,` },
      { number: 5, text: `those who are seen, and those who are unseen, those who live far away, those who are near,
those who are born, and those who still seek birth may all beings in their hearts be happy!` },
      { number: 6, text: `Let him not deceive another nor despise anyone anywhere. In anger or ill will let him not wish another ill.` },
      { number: 7, text: `Just as a mother would protect her only child with her life even so let one cultivate a boundless love towards all beings.` },
      { number: 8, text: `Let him radiate boundless love towards the entire world — above, below, and across — unhindered, without ill will, without enmity.` },
      { number: 9, text: `Standing, walking, sitting or reclining, as long as he is awake, let him develop this mindfulness. This, they say, is 'Noble Living' here.` },
      { number: 10, text: `Not falling into wrong views — being virtuous, endowed with insight, having removed greed towards sense pleasures, — verily never again will he return to conceive in a womb.` },
    ],
    translationMyanmar: [
      { number: 0, text: `ထို (ကာကွယ်မှု) ၏ တန်ခိုးကြောင့် ယက္ခများသည် ကြောက်မက်ဖွယ် (မြင်ကွင်းများ) ကို ပေါ်လွင်အောင် မလုပ်နိုင်ဘဲ၊ နေ့ရောညပါ လုံ့လဝီရိယရှိရှိ အိပ်ပျော်ပြီး အိပ်နေစဉ် မကောင်းသောအရာကို မမြင်နိုင်ဟု ကျင့်ကြံခြင်းဖြင့် ထိုကာကွယ်မှုကို ကျွန်ုပ်တို့ ရွတ်ဆိုပါမည်။` },
      { number: 1, text: `(မိမိ၏) ကောင်းကျိုးချမ်းသာကို ကျွမ်းကျင်ပြီး ထိုငြိမ်သက်ခြင်း (နိဗ္ဗာန်) ကို ရရှိလိုသူသည် ဤသို့ပြုမူသင့်သည်- လိမ္မာပါးနပ်သူ၊ ဖြောင့်မတ်သူ၊ အလွန်ဖြောင့်မတ်သူ၊ နာခံသူ၊ နူးညံ့သိမ်မွေ့သူ၊ နှိမ့်ချသူ ဖြစ်ရမည်။` },
      { number: 2, text: `ကျေနပ်ရောင့်ရဲသူ၊ ထောက်ပံ့ရလွယ်ကူသူ၊ တာဝန်အနည်းငယ်သာရှိသူ၊ ရိုးရှင်းသော အသက်မွေးဝမ်းကျောင်းလုပ်ငန်းရှိသူ၊ အာရုံငါးပါးကို ထိန်းချုပ်နိုင်သူ၊ သတိရှိသူ၊ ယဉ်ကျေးသူ၊ မိသားစုနှင့် ပေါင်းသင်းဆက်ဆံလိုစိတ်မရှိသူ ဖြစ်ရမည်။` },
      { number: 3, text: `ပညာရှိများ ဆုံးမနိုင်သည့် အနည်းငယ်မျှသော မကောင်းမှုကိုမျှ မပြုလုပ်ပါစေနှင့်။ (ထိုသူသည် တွေးတောပါစေ) 'သတ္တဝါအားလုံး ပျော်ရွှင်ကြပါစေ။ ချမ်းသာသောစိတ် ရှိကြပါစေ' ဟု တွေးတောပါစေ။` },
      { number: 4, text: `မည်သည့်သက်ရှိသတ္တဝါမဆို - အားနည်းသည်ဖြစ်စေ၊ ခွန်အားကြီးသည်ဖြစ်စေ၊ (သို့မဟုတ် ရှာဖွေသူများနှင့် ရရှိသူများ) ရှည်သည်ဖြစ်စေ၊ ဝသည်ဖြစ်စေ၊ အလတ်စားသည်ဖြစ်စေ၊ တိုသည်ဖြစ်စေ၊  သေးသည်ဖြစ်စေ၊ ကြီးသည်ဖြစ်စေ၊` },
      { number: 5, text: `မြင်နေရသူများ၊ မမြင်ရသေးသူများ၊ ဝေးလံသောအရပ်တွင် နေထိုင်သူများ၊ အနီးတွင် နေထိုင်သူများ၊ မွေးဖွားလာသူများနှင့် မွေးဖွားခြင်းကို ရှာဖွေနေဆဲသူများ စိတ်နှလုံးထဲရှိ သတ္တဝါအားလုံး ပျော်ရွှင်ကြပါစေ။` },
      { number: 6, text: `သူသည် အခြားသူတစ်ဦးကို မလှည့်ဖြားပါစေနှင့်၊ မည်သည့်နေရာတွင်မဆို မည်သူ့ကိုမျှ မထီမဲ့မြင်မပြုပါစေနှင့်။ ဒေါသ သို့မဟုတ် မကောင်းမှုဖြင့် အခြားသူတစ်ဦးကို မကောင်းမှုပြုလိုခြင်း မပြုပါစေနှင့်။` },
      { number: 7, text: `မိခင်သည် မိမိ၏တစ်ဦးတည်းသော ရင်သွေးကို အသက်ဖြင့် ကာကွယ်သကဲ့သို့ပင် သတ္တဝါအားလုံးအပေါ် အကန့်အသတ်မရှိသော မေတ္တာကို မွေးမြူပါစေ။` },
      { number: 8, text: `အထက်၊ အောက်၊ တစ်ဖက်တစ်ချက်ရှိ လောကတစ်ခုလုံးအပေါ် အကန့်အသတ်မရှိသော မေတ္တာကို ဖြန့်ကျက်ပါစေ။ မကောင်းသော အလိုမရှိ၊ ရန်ငြိုးမရှိဘဲ။` },
      { number: 9, text: `ရပ်နေခြင်း၊ လမ်းလျှောက်ခြင်း၊ ထိုင်နေခြင်း၊ လဲလျောင်းနေခြင်း၊ နိုးနေသမျှကာလပတ်လုံး ဤသတိပဋ္ဌာန်ကို မွေးမြူပါစေ။ ဤသည်မှာ 'မြင့်မြတ်သောဘဝ' ဖြစ်သည်ဟု ဆိုကြသည်။` },
      { number: 10, text: `မှားယွင်းသောအမြင်များ - သီလနှင့်ပြည့်စုံခြင်း၊ ဉာဏ်အမြင်နှင့်ပြည့်စုံခြင်း၊ ကာမဂုဏ်အာရုံများအပေါ် လောဘကို ဖယ်ရှားခြင်း - ထိုသူသည် နောက်တစ်ဖန် သားအိမ်၌ ပဋိသန္ဓေတည်ရန် ပြန်မလာတော့ပေ။` },
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
  4: {
    folderName: '04_khandha_sutta',
    paliRoman: [
      { number: 1, text: `Sabbāsīvisajātīnaṁ dibbamantāgadaṁ viya,
yaṁ nāseti visaṁ ghoraṁ sesañ-cāpi parissayaṁ.` },
      { number: 2, text: `Āṇākkhettamhi sabbattha, sabbadā sabbapāṇinaṁ,
sabbaso pi nivāreti, parittaṁ taṁ bhaṇāmahe.` },
      { number: 3, text: `Virūpakkhehi me mettaṁ, mettaṁ Erāpathehi me,
Chabyāputtehi me mettaṁ, mettaṁ Kaṇhāgotamakehi ca.` },
      { number: 4, text: `Apādakehi me mettaṁ, mettaṁ dvipādakehi me,
catuppadehi me mettaṁ, mettaṁ bahuppadehi me.` },
      { number: 5, text: `Mā maṁ apādako hiṁsi, mā maṁ hiṁsi dvipādako,
mā maṁ catuppado hiṁsi, mā maṁ hiṁsi bahuppado.` },
      { number: 6, text: `Sabbe sattā, sabbe pāṇā, sabbe bhūtā ca kevalā,
sabbe bhadrāni passantu, mā kañci pāpam-āgamā.` },
      { number: 7, text: `Appamāṇo Buddho! Appamāṇo Dhammo!
Appamāṇo Saṅgho! Pamāṇavantāni sirīsapāni,
ahivicchikā, satapadī, uṇṇānābhī, sarabū, mūsikā.` },
      { number: 8, text: `Katā me rakkhā, katā me parittā, paṭikkamantu bhūtāni!
Sohaṁ namo Bhagavato, namo sattannaṁ Sammāsambuddhānaṁ.` },
    ],
    paliMyanmar: [
      { number: 1, text: `သဗ္ဗာသီဝိသ ဇာတီနံ၊ ဒိဗ္ဗမန္တာဂဒံ ဝိယ။
ယံ နာသေတိ ဝိသံ ဃောရံ၊ သေသဉ္စာပိ ပရိဿယံ။` },
      { number: 2, text: `အာဏာက္ခေတ္တမှိ သဗ္ဗတ္ထ၊ သဗ္ဗဒါ သဗ္ဗပါဏိနံ။
သဗ္ဗသောပိ နိဝါရေတိ၊ ပရိတ္တံ တံ ဘဏာမ ဟေ။` },
      { number: 3, text: `ဝိရူပက္ခေဟိ မေ မေတ္တံ၊ မေတ္တံ ဧရာပထေဟိ မေ။
ဆဗျာပုတ္တေ ဟိ မေ မေတ္တံ၊ မေတ္တံ ကဏှာ ဂေါတမ ကေဟိစ။` },
      { number: 4, text: `အပါဒကေဟိ မေ မေတ္တံ၊ မေတ္တံဒွိပါ ဒကေဟိ မေ။
စတုပ္ပဒေဟိ မေ မေတ္တံ၊ မေတ္တံ ဗဟုပ္ပဒေ ဟိ မေ။` },
      { number: 5, text: `မာ မံ အပါဒကော ဟိံသိ၊ မာ မံ ဟိံသိ ဒွိပါဒကော။
မာ မံ စတုပ္ပဒေါ ဟိံသိ၊ မာ မံ ဟိံသိ ဗဟုပ္ပဒေါ။` },
      { number: 6, text: `သဗ္ဗေ သတ္တာ သဗ္ဗေ ပါဏာ၊ သဗ္ဗေ ဘူတာ စ ကေဝလာ။
သဗ္ဗေ ဘဒြာနိ ပဿန္တု၊ မာ ကိဉ္စိ ပါပ မာဂမာ။` },
      { number: 7, text: `အပ္ပမာဏော ဗုဒ္ဓေါ၊ အပ္ပမာဏော ဓမ္မော။
အပ္ပမာဏော သံဃော၊ ပမာဏဝန္တာနိ သရီသပါနိ။
အဟိ ဝိစ္ဆိကာ သတပဒီ၊ ဥဏ္ဏနာဘီ သရဗူ မူသိကာ။` },
      { number: 8, text: `ကတာ မေ ရက္ခာ ကတံ မေ ပရိတ္တံ၊ ပဋိက္ကမန္တု ဘူတာနိ။
သောဟံ နမော ဘဂဝတော၊ နမော သတ္တန္နံ သမ္မာသမ္ဗုဒ္ဓါနံ။` },
    ],
    translationEnglish: [
      { number: 1, text: `To all kinds of poisonous snakes it is like the medicine of a divine charm,
it destroys terrible poisons and all other dangers.` },
      { number: 2, text: `In this order’s domain, (which is) everywhere, always, for all living creatures,
it thoroughly wards off (all dangers), we will recite that safeguard.` },
      { number: 3, text: `I am friendly with the Virūpakkhas, with the Erāpathas I am friendly,
I am friendly with the Chabyāputtas, and friendly with the Kaṇhāgotamakas.` },
      { number: 4, text: `I am friendly with those without feet, with those with two feet I am friendly,
I am friendly with those with four feet, with those with many feet I am friendly.` },
      { number: 5, text: `May the one without feet not hurt me, may the one with two feet not hurt me,
may the one with four feet not hurt me, may the one with many feet not hurt me.` },
      { number: 6, text: `May all beings, all living creatures, all who are born, in their entirety,
may all see prosperity, may nothing bad come to anyone.` },
      { number: 7, text: `Infinite (in virtue) is the Buddha, infinite is the Dhamma, infinite is the Sangha. Finite are creeping creatures - snakes, scorpions, centipedes, spiders, lizards, and rats.` },
      { number: 8, text: `I have made this protection, I have made this safeguard, may (all these) beings epart from me!
I revere the Fortunate One, I revere the seven Supreme Buddhas.` },
    ],
    translationMyanmar: [
      { number: 1, text: `အဆိပ်ပြင်းသော မြွေအမျိုးမျိုးအတွက် ၎င်းသည် နတ်ဝိဇ္ဇာ၏ ဆေးကဲ့သို့ဖြစ်ပြီး၊ ကြောက်မက်ဖွယ်ကောင်းသော အဆိပ်များနှင့် အခြားအန္တရာယ်အားလုံးကို ဖျက်ဆီးပစ်သည်။` },
      { number: 2, text: `ဤအစီအစဉ်၏ နယ်ပယ်တွင်၊ (နေရာတိုင်း၊ အမြဲတမ်း၊ သက်ရှိသတ္တဝါအားလုံးအတွက်)၊ ၎င်းသည် (အန္တရာယ်အားလုံးကို ကောင်းစွာ ကာကွယ်စောင့်ရှောက်သည်)၊ ကျွန်ုပ်တို့သည် ထိုကာကွယ်မှုကို ရွတ်ဆိုပါမည်။` },
      { number: 3, text: `ဝိရူပက္ခများနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်၊ ဧရာပထများနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်၊

သဗျပုတ္တများနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်၊ ကဏန်းဟော်တမက်စ်များနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်။` },
      { number: 4, text: `ခြေမရှိသူများနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်၊ ခြေနှစ်ချောင်းရှိသူများနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်၊
ခြေလေးချောင်းရှိသူများနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်၊ ခြေများသူများနှင့် ကျွန်ုပ်သည် မိတ်ဆွေဖွဲ့သည်။` },
      { number: 5, text: `ခြေမရှိသူသည် ကျွန်ုပ်ကို မထိခိုက်စေပါစေနှင့်၊ ခြေနှစ်ချောင်းရှိသူသည် ကျွန်ုပ်ကို မထိခိုက်စေပါစေနှင့်၊
ခြေလေးချောင်းရှိသူသည် ကျွန်ုပ်ကို မထိခိုက်စေပါစေနှင့်၊ ခြေများသူသည် ကျွန်ုပ်ကို မထိခိုက်စေပါစေနှင့်။` },
      { number: 6, text: `သတ္တဝါအားလုံး၊ မွေးဖွားလာသူအားလုံး၊ အလုံးစုံသော ကောင်းကျိုးချမ်းသာကို တွေ့မြင်ကြပါစေ၊ မည်သူ့ကိုမျှ မကောင်းသောအရာ မရောက်ကြပါစေ။` },
      { number: 7, text: `အနန္တ (သီလ) သည် ဗုဒ္ဓ၊ အနန္တ (တရား) သည် ဓမ္မ၊ အနန္တ (တရား) သည် သံဃာ။ မြွေ၊ ကင်းမြီးကောက်၊ ကင်းခြေများ၊ ပင့်ကူများ၊ ပုတ်သင်ညိုများနှင့် ကြွက်များသည် အနန္တဖြစ်သည်။` },
      { number: 8, text: `ငါသည် ဤအကာအကွယ်ကို ပြုလုပ်ပြီးပြီ၊ ဤအကာအကွယ်ကို ပြုလုပ်ပြီးပြီ၊ ဤသတ္တဝါအားလုံးသည် ငါ့ထံမှ ထွက်ခွာသွားပါစေ။
ကံကောင်းတော်မူသော မြတ်စွာဘုရား၊ အနန္တရဗုဒ္ဓ ခုနစ်ပါးကို ကျွန်ုပ် ရိုသေလေးစားပါ၏။` },
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
  5: {
    folderName: '05_mora_sutta',
    paliRoman: [
      { number: 1, text: `Pūrentaṁ Bodhisambhāre nibbattaṁ morayoninaṁ.
Yena saṁvihitārakkhaṁ Mahāsattaṁ vane carā
cirassaṁ vāyamantā pi, neva sakkhiṁsu gaṇhituṁ.
“Brahmamantan”-ti akkhātaṁ, parittaṁ taṁ bhaṇāmahe.` },
    ],
    paliMyanmar: [
      { number: 1, text: `ပူရေန္တံ ဗောဓိသမ္ဘာရေ၊ နိဗ္ဗတ္တံ မောရ ယောနိယံ။
ယေန သံဝိဟိတာ ရက္ခံ၊ မဟာသတ္တံ ဝနေစရာ။` },
      { number: 2, text: `စိရဿံ ဝါယမန္တာပိ၊ နေဝ သက္ခိံသု ဂဏှိတုံ။
“ဗြဟ္မမန္တ” န္တိ အက္ခာတံ၊ ပရိတ္တံ တံ ဘဏာမ ဟေ။` },
      { number: 3, text: `ဥဒေတယံ စက္ခုမာ ဧကရာဇာ၊ ဟရိဿဝဏ္ဏော ပထဝိပ္ပဘာသော။
တံ တံ နမဿမိ ဟရိဿဝဏ္ဏံ ပထဝိပ္ပ ဘာသံ၊
တယာဇ္ဇ ဂုတ္တာ ဝိဟရေမု ဒိဝသံ။` },
      { number: 4, text: `ယေ ဗြဟ္မဏာ ဝေဒဂူ သဗ္ဗဓမ္မေ၊
တေ မေ နမော တေ စ မံ ပါလယန္တု။
နမတ္ထု ဗုဒ္ဓါနံ နမတ္ထု ဗောဓိယာ၊
နမော ဝိမုတ္တာနံ နမော ဝိမုတ္တိယာ။
ဣမံ သော ပရိတ္တံ ကတွာ၊ မောရော စရတိ ဧသနာ။` },
      { number: 5, text: `အပေတယံ စက္ခုမာ ဧကရာဇာ။ ဟရိဿဝဏ္ဏော ပထဝိပ္ပဘာသော။
တံ တံ နမဿာမိ ဟရိဿဝဏ္ဏံ ပထဝိပ္ပ ဘာသံ၊
တယာဇ္ဇ ဂုတ္တာ ဝိဟရေမု ရတ္တိံ။` },
      { number: 6, text: `ယေ ဗြာဟ္မဏာ ဝေဒဂူ သဗ္ဗဓမ္မေ။
တေ မေ နမော တေစ မံ ပါလယန္တု။
နမတ္ထု ဗုဒ္ဓါနံ နမတ္ထု ဗောဓိယာ၊
နမော ဝိမုတ္တာနံ နမော ဝိမုတ္တိယာ။
ဣမံ သော ပရိတ္တံ ကတွာ၊ မောရော ဝါသ မကပ္ပယိ။
မောရသုတ္တံ နိဋ္ဌိတံ။ ။` },
    ],
    translationEnglish: [
      { number: 1, text: `There rises the golden hued one, the one who has sight, the one who is sole monarch, the one who illuminates the earth (it is the sun that is being addressed). I adore thee, the golden hued one who illuminates the earth (it is the sun that is being addressed). I adore thee, the golden hued one who illuminates the earth. Protected by thee we live this day safe and secure.` },
      { number: 2, text: `May my adoration be to those Brahmanas[2] (the Buddhas) who have attained Enlightenment by comprehending all dhammas. May they protect me. May my adoration be to the Buddhas (of the past), to their Enlightenment (the Four Paths and the Four Fruits). May my adoration be to those supremely secured from bondage (the Buddhas) and to their Deliverance. Having made this protection, the peacock goes about seeking (food).` },
      { number: 3, text: `There descends the golden hued one, the one who has sight, the one who is sole monarch, the one who illuminates the earth. I adore thee, the golden hued one who illuminates the earth. Protected by thee we live this night safe and secure.` },
      { number: 4, text: `May my adoration be to those Brahmanas (the Buddhas) who have attained Enlightenment by comprehending all dhammas. May they protect me. May my adoration be to the Buddhas (of the past), to their Enlightenment. May my adoration be to those supremely secured from bondage (the Buddhas) and to their Deliverance. Having made this protection the peacock spent his life happily.` },
    ],
    translationMyanmar: [
      { number: 1, text: `ရွှေရောင်ရှိသော အရှင်၊ မျက်စိအမြင်ရှိသော၊ တစ်ပါးတည်းသော မင်းကြီး၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော (နေမင်း) ကြွလာတော်မူ၏။ အကျွန်ုပ်သည် သင့်အား ရှိခိုးပါ၏။ ရွှေရောင်ရှိသော အရှင်၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော (နေမင်း) ကြွလာတော်မူ၏။ ရွှေရောင်ရှိသော အရှင်၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော (နေမင်း) ကြွလာတော်မူ၏။ ရွှေရောင်ရှိသော အရှင်၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော အကျွန်ုပ်သည် သင့်အား ရှိခိုးပါ၏။ အရှင်၏ စောင့်ရှောက်မှုကြောင့် ယနေ့တွင် ကျွန်ုပ်တို့သည် ဘေးကင်းလုံခြုံစွာ နေထိုင်ရပါ၏။` },
      { number: 2, text: `အလုံးစုံသော တရားတို့ကို နားလည်၍ ဉာဏ်အလင်းရရှိတော်မူသော ဗြဟ္မဏများ (ဗုဒ္ဓများ) အား အကျွန်ုပ်၏ ရိုသေလေးစားမှု ရှိပါစေ။ သူတို့သည် အကျွန်ုပ်အား စောင့်ရှောက်ကြပါစေ။ (အတိတ်ကာလက) ဗုဒ္ဓများ၊ ဉာဏ်အလင်းရရှိတော်မူသော (လမ်းလေးပါးနှင့် အသီးလေးမျိုး) အား အကျွန်ုပ်၏ ရိုသေလေးစားမှု ရှိပါစေ။ ကျွန်ဘဝမှ လွတ်မြောက်တော်မူသော (ဗုဒ္ဓများ) အား အကျွန်ုပ်၏ ရိုသေလေးစားမှု ရှိပါစေ။ ဤကာကွယ်မှုကို ပြုလုပ်ပြီးနောက် ဒေါင်းသည် (အစာ) ရှာဖွေရန် လှည့်လည်သွားလာ၏။` },
      { number: 3, text: `ရွှေရောင်ရှိသော အရှင်၊ မျက်စိအမြင်ရှိသော၊ တစ်ပါးတည်းသော မင်းကြီး၊ ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော ထိုအရပ်သို့ ဆင်းသက်တော်မူ၏။ ရွှေရောင်ကမ္ဘာမြေကို ထွန်းလင်းစေတော်မူသော သင့်အား ကျွန်ုပ် ကိုးကွယ်ပါ၏။ သင့်အား ကာကွယ်စောင့်ရှောက်တော်မူခြင်းဖြင့် ဤညတွင် ဘေးကင်းလုံခြုံစွာ နေထိုင်ပါ၏။` },
      { number: 4, text: `အလုံးစုံသော ဓမ္မများကို နားလည်ခြင်းဖြင့် ဉာဏ်အလင်းရရှိတော်မူသော ဗြဟ္မဏများ (ဗုဒ္ဓများ) ကို ကျွန်ုပ်၏ ကိုးကွယ်ရာ ဖြစ်ပါစေ။ ၎င်းတို့သည် ကျွန်ုပ်ကို ကာကွယ်စောင့်ရှောက်ကြပါစေ။ (အတိတ်ကာလက) ဗုဒ္ဓများ၊ ဉာဏ်အလင်းရရှိတော်မူသော သူတို့အား ကျွန်ုပ်၏ ကိုးကွယ်ရာ ဖြစ်ပါစေ။ (ဗုဒ္ဓများ) ကျွန်ဘဝမှ လွတ်မြောက်ခြင်းနှင့် လွတ်မြောက်ခြင်းမှ အလွန်လုံခြုံတော်မူသော သူတို့အား ကျွန်ုပ်၏ ကိုးကွယ်ရာ ဖြစ်ပါစေ။ ဤအကာအကွယ်ကို ပြုလုပ်ပြီးနောက် ဒေါင်းသည် သူ၏ဘဝကို ပျော်ရွှင်စွာ ဖြတ်သန်းခဲ့သည်။` },
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
  9: {
    folderName: '09_angulimala_sutta',
    paliRoman: [
      { number: 1, text: `Parittam yam bhanantassa,
nisinnatthanadhovanam;
udakampi vinaseti,
sabbameva parissayam.` },
      { number: 2, text: `Sotthina gabbhavuthanam,
yanca sadheti tankhane;
therassa Angulimalassa,
Lokanathena bhasitam;
kappatthayim mahatejam,
parittam tam bhanama he.` },
      { number: 3, text: `Yato' ham bhagini ariyaya jatiya jato,
nabhijanami sancicca
panam jivita voropeta;
tena saccena sotthi te hotu
sotthi gabbhassa.` },
    ],
    paliMyanmar: [
    ],
    translationEnglish: [
      { number: 1, text: `Even the water that rinsed
the seat of the Elder who
recited this discourse of protection
did eradicate all the dangerous difficulties.` },
      { number: 2, text: `That very paritta discourse has the power
to accomplish the labour of child-birth healthily.
Explained to Venerable Angulimala,
the great spiritual power of this
will last long for the entire aeon.
Let us recite this discourse of protection.` },
      { number: 3, text: `Oh sister, since I was born of the Ariyan birth.
I have not intentionally
deprived any living thing of life
By the truth of this, may there be
happiness and well-being
to you and to your unborn child.` },
    ],
    translationMyanmar: [
    ],
    preambleEnglish: ``,
    preambleMyanmar: ``,
  },
};

export default parittaContent;
